### ISSUE TITLE
Add sql HasPrefix and HasSuffix string functions

### ISSUE THREAD

**Issue by dgeorgievski** [cloudevents/sdk-go#1045]
I have a frequent use case where CloudEvents would need to be filtered and routed using a rule like this
`"HasPrefix(type, 'dev.tekton.event')"`

HasPrefix and -Suffix should have the same behavior like Go's functions with the same name from the strings package.

I plan to submit a PR next with a suggested implementation for these functions.

**Comment by duglin** [comment]
pinging @Cali0707 and @lionelvillard for thoughts

**Comment by Cali0707** [comment]
Is there a reason why an expression such as `type LIKE dev.tekton.event%` wouldn't work for this use case?

**Comment by Cali0707** [comment]
Another idea (which I would be happy to work on contributing code for) is we can expose the AddFunction api, letting users define their own functions and provide them to the sdk on their own

**Comment by dgeorgievski** [comment]
> Is there a reason why an expression such as `type LIKE dev.tekton.event%` wouldn't work for this use case?
> 
From what I see LIKE expression involves a conversion to a regex expression which I'd expect to be less performant in a large volume of stream of events. 

> IMO, I'd prefer to keep the CESQL API more in line with normal SQL, rather than go standard lib functions
If that is a goal, I agree it doesn't make sense to add go standard lib functions, although that would be a nice extension of the API :-).

I could also use the LEFT function instead of LIKE, but then I have to count the prefix characters.
`left(type, 16) = 'dev.tekton.event'`

**Comment by dgeorgievski** [comment]
> Another idea (which I would be happy to work on contributing code for) is we can expose the AddFunction api, letting users define their own functions and provide them to the sdk on their own

That is a great idea, which reminded me of another question that might be little off topic

Are there any plans to process events as streams? It would be very helpful to be able to process events in pipelines like this
`event |> f |> g |> ...`

Where f, g are functions that could perform among other things
- filtering
- compounding
- transformations
- splitting 
- sending events to different sinks

**Comment by Cali0707** [comment]
> From what I see LIKE expression involves a conversion to a regex expression which I'd expect to be less performant in a large volume of stream of events.

Yeah I also noticed that when I started working on the CESQL stuff. Maybe a better solution here would be to just fix the implementation of `LIKE` to not use regex and use a better algorithm?

I guess to summarize my thinking, we should:
1. Fix the `LIKE` expression implementation
2. Expose the `AddFunction` API

@dgeorgievski do these two points sound reasonable for your use case? Also would you be interested in working on any of this?

**Comment by Cali0707** [comment]
> Are there any plans to process events as streams? It would be very helpful to be able to process events in pipelines like this
event |> f |> g |> ...

Not that I know of, maybe others can comment there (@duglin ?). I know that you can build workflows that can do that in Knative with https://knative.dev/docs/eventing/flows/ or Brokers + Triggers, but it may take a bit of work (for transparency I contribute to Knative so I may be biased towards using that as a solution)

**Comment by dgeorgievski** [comment]
> @dgeorgievski do these two points sound reasonable for your use case? Also would you be interested in working on any of this?

Yes, both points would be useful in my use case. I am interested in working on both but would like to address `AddFunction` probably first.

**Comment by Cali0707** [comment]
Cool, maybe we can split it 50/50 then @dgeorgievski - I can work on the LIKE improvements and you can work on the AddFunction?

**Comment by dgeorgievski** [comment]
I believe this issue could be closed then
