### ISSUE TITLE
Expose AddFunction API for CESQL Parser

### ISSUE THREAD

**Issue by Cali0707** [cloudevents/sdk-go#1047]
As discussed in #1045 , it would be good to provide end users of the SDK the ability to add custom functions to the CESQL parser and runtime.

I think this would probably start with changes in https://github.com/cloudevents/sdk-go/blob/f97061a7e72b17f63120aa553123edb28c49e490/sql/v2/runtime/functions_resolver.go#L23, but it will likely need changes in other areas as well

**Comment by Cali0707** [comment]
@duglin I believe @dgeorgievski has offered to contribute a PR for this

**Comment by dgeorgievski** [comment]
Just for the record I am willing to work on this PR

**Comment by duglin** [comment]
thanks @dgeorgievski

**Comment by dgeorgievski** [comment]
Hi @duglin, 

Just curious how long it would take to finalize the review of the PR. I hope the code owners are not gone for the summer break :-)

**Comment by lionelvillard** [comment]
I can take a look at it

**Comment by Cali0707** [comment]
I believe this is complete now, closing here...
