### ISSUE TITLE
[500 Internal Server Error] in default-broker-ingress pod

### ISSUE THREAD

**Issue by rashiga** [cloudevents/sdk-go#124]
The event watcher and the broker ingress and filter are running.  
(kubectl get pods)
NAME                                                         READY   STATUS             RESTARTS   AGE
default-broker-filter-694464b4f4-j4kg7        2/2     Running            1                17h
default-broker-ingress-55bbb8555b-ck9lw   2/2     Running            1               17h
glusterfs-8przp                                               1/1     Running            0              17h
glusterfs-ddj9h                                               1/1     Running            5              13d
glusterfs-jpv2p                                                1/1     Running            0                8d
heketi-576bb8967c-vgm94                             0/1     CrashLoopBackOff   0          8d
testevents-c2m8m-xzd8s-75fd6bcf48-zbjzn   2/2     Running            0              17h

The broker.yaml which I applied is -
apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: default
  namespace: default
spec:
  channelTemplate:
    provisioner:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: ClusterChannelProvisioner
      name: in-memory-channel

The logs of the ingress pod gives the following error -
(kubectl logs default-broker-ingress-55bbb8555b-ck9lw -c ingress)
"got an error from receiver fn: error sending cloudevent: Status[500 Internal Server Error] "

The logs of the testevents pod is flusshing this error -
 (kubectl logs testevents-c2m8m-xzd8s-75fd6bcf48-zbjzn -c source)
"{"level":"info","ts":1557311356.807349,"logger":"fallback","caller":"kubernetesevents/adapter.go:113","msg":"Event delivery failed: error sending cloudevent: Status[400 Bad Request] ","eventID":"21c4c723-717c-11e9-91cf-14feb50fb61e","sink":"http://default-broker.default.svc.cluster.local/"} "

Regards
Rashi

**Comment by n3wscott** [comment]
the upstream client returned an error and send a 500. This is working as intended unless you can point to a line in the SDK.
