### ISSUE TITLE
Double quote for extensions attributes in binary encoding (http and amqp)

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/sdk-go#125]
When forwarding a CloudEvent, that was received in structured mode, with http or amqp binary mode, the values of extension attributes are double quoted like
`cause: ""d282c453-8ccd-4f29-b754-3344cb878dc5""`
I think it might be due to the code lines in [function toHeaders](https://github.com/cloudevents/sdk-go/blob/56931988abe3adf6792b5c6e575ee5f573e9ccbc/pkg/cloudevents/transport/amqp/codec.go#L122):
```	
		if s, ok := v.(string); ok {
			h[prefix+k] = s
			continue
		}
```
In [jsoncodec.go](https://github.com/cloudevents/sdk-go/blob/56931988abe3adf6792b5c6e575ee5f573e9ccbc/pkg/cloudevents/codec/jsoncodec.go#L264) extensions are copied from the map `raw`. Therefore they are of type []byte. When converting the event to binary, the type assertion v.(string) fails.

**Comment by n3wscott** [comment]
I am not seeing this when I run my code. 

How do you set the cloudevent up? What is the code you use to make the event?

**Comment by deissnerk** [comment]
I've got a trigger implemented that uses the sdk for encoding/decoding of CloudEvents. The HTTP return message of the function gets forwarded back to AMQP. If the function returns the event in HTTP structured mode, the problem occurs, if it returns HTTP binary, everything is ok.

**Comment by n3wscott** [comment]
yeah this is an interesting problem. Some transports allow responses, others do not. What should happen?

**Comment by deissnerk** [comment]
I don't think my problem was related to the fact that the CE was in an HTTP response. I only used the SDK for encoding/decoding. When parsing a JSON CE, the raw values (including the ") are stored. When parsing a binary mode event, `json.Unmarshal()` is called. When passing the event on in binary mode, there is always `json.Marshal(v)` called for the value.

**Comment by n3wscott** [comment]
Doublequotes are dropped from the spec! 🎉

**Comment by deissnerk** [comment]
Yes, I was referring to that in #143.

**Comment by slinkydeveloper** [comment]
This one is still valid?

**Comment by n3wscott** [comment]
We fixed this with the new types and better type support and dropped 0.2
