### ISSUE TITLE
Need a way to tell when a Transport is ready

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#131]
I can't see any way to tell when a transport is "ready", which is critical if you need to query the transport state. For example in transport.http there is this comment:

// GetPort returns the port the transport is active on.
// .Port can be set to 0, which means the transport selects a port, GetPort
// allows the transport to report back the selected port.

That is actually not possible: while one goroutine is blocked in StartReceiver(), there's no way for another goroutine to tell when it can call GetPort() - it has to happen after the net.Listen() call.

Proposed solution (I'll write a PR if this seems acceptable), 2 versions the clean and compatible:

// clean but incompatible, adding a method to Transport interface invalidates existing transports:
interface Transport {
  ...
  // Ready returns a channel that closes when StartReceiver() has completed any 
  // set up (listening, connecting etc.) and is waiting to receive events. It always
  //  closes before StartReceiver() returns, including in the event of an error.
  Ready() <-chan struct{}
}

// backwards compatible version, separate interface. Transports are strongly encouraged to 
// implement it but existing transports won't be broken.
interface Readyer {
  Ready() <-chan struct{}
}

**Comment by matzew** [comment]
> backwards compatible version, separate interface

seems like a safe harbor

**Comment by alanconway** [comment]
I have a rethink on the solution to this: "Ready" is a very transport-specific concept, some transports might not even have such a phase. So instead of adding this to the Tranport interface, I propose to update the HTTP transport (and any others with similar issues) as follows:

l := net.Listen(...)
transport := http.New(WithListener(l))

That gives the user full control (if they wish) over the listener, including the ability to get a Listen(":0") address from l.Addr().  It also allows listening on specific interfaces on a multi-homed host (which is currently impossible) and listening specifically for tpc6 or tcp4 trafic. And it is backwards compatible :)

We'd want to encourage something similar on any transport that uses a listener, I'll have a look at the existing ones.

**Comment by n3wscott** [comment]
you can already give port 0 in http options. 

Let me look more at this...

**Comment by alanconway** [comment]
On Thu, Jun 6, 2019 at 4:50 PM Scott Nichols <notifications@github.com>
wrote:

> you can already give port 0 in http options.
>
You can, and there is a GetPort() method - the problem is there is no pontt
at which you can call that method.
```
go func() { x.StartReceiver(...) }
port := x.GoPort() // WRONG:  the concurrent StartReceiver() may not have
passed net.Listen() yet.
// There's no sensible way to wait till StartReceiver gets to Listen()
```

Rather than complicating the Transport interface I suggest we allow users
to do more setup using standard net/http before creating the Transport - in
this case to pass in  their own Listener.
That also solves another problem: currently there's no way to specify the
listening network or host - that's important on multi-homed hosts. Passing
in a listener gives the user the full power of the net package to set it up
as they wish.

This is the same pattern used by http.Server -  ListenAndServe() if you
just want to provide a port, Serve(Listener) if you want more control of
the listener.

Let me look more at this...

**Comment by n3wscott** [comment]
I wonder if this is a time to introduce message channels that can be passed to the transport via options. An error channel and an fyi channel? (in addition to the PR you have pending). 

Then the FYI channel could send a transport state update messages. (Ready, Failed, restarting...?)

**Comment by alanconway** [comment]
On Fri, Jun 14, 2019 at 10:26 AM Scott Nichols <notifications@github.com>
wrote:

> I wonder if this is a time to introduce message channels that can be
> passed to the transport via options. An error channel and an fyi channel?
> (in addition to the PR you have pending).
>

I think that's more complicated than need be. My PR solves the problem a
different way - you can control listening when you create the transport, so
there's no need to complicate the transport interface. I like that better
since the notion of "ready" will be different or irrelevant for some
transports.

> Then the FYI channel could send a transport state update messages. (Ready,
> Failed, restarting...?)
>
I think it's important not to bring too much information up into the
generic interface. So having this error handling  before/during transport
creation, when we're still in transport-specific code seems better.
