### ISSUE TITLE
Why use pkg/cloudevents dir?

### ISSUE THREAD

**Issue by thinkerou** [cloudevents/sdk-go#135]
Hi, @n3wscott 
why use `sdk-go/pkg/cloudevents/*` dir not `sdk-go/*`? what's the good? thanks!

**Comment by n3wscott** [comment]
I am following standard strongly structured golang packages with cmd, pkg, hack, etc... 

I add `alias.go` to the root so you can use http clients directly.

**Comment by thinkerou** [comment]
@n3wscott OK, thanks!

**Comment by n3wscott** [comment]
I thought about this more and you are right. there is no reason to have a cloudevents directory inside of pkg. 

Let's clear the PR backlog and fix this. Thanks for the question.

**Comment by thinkerou** [comment]
If interface un-export, maybe we should put `internal` dir.

**Comment by lucperkins** [comment]
@n3wscott I'm happy to handle this. I'll submit a PR in the coming days.

**Comment by slinkydeveloper** [comment]
This was addressed in v2 of the sdk
