### ISSUE TITLE
Use of cloudevent HTTP transport as codec only

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#140]
There are 2 use cases for cloudevents transport:

1. As message codec only: to translate Event to/from the native transport libraries message type (e.g. for HTTP this would be http.Request and http.Response) This is for applications that want full access to features of the underlying transport library (e.g. net/http) and decisions about dispatching, use of goroutines, memory management etc.

2. As a generic API for transport-neutral applications that want to allow replaceable transports. This is for applications that care most about isolating themselves from transport details. It is ok (when necessary) to limit access to the underlying transport and make implementation choices - the goal is encapsulation rather than total freedom.

The HTTP code provides 2. and is close to 1.  it is missing some convenience methods, e.g.

    func (m *Message) toRequest(r *http.Request)

This issue serves for HTTP, other issues referencing this can be raised for other transports.

**Comment by n3wscott** [comment]
I am open to this idea. Some want this feature for sure. I get questions like "I have a req, can i haz cloudevent?"

**Comment by alanconway** [comment]
What are your thoughts on the PR? I'd like to agree on a good API approach on HTTP before I run around and do something similar for AMQP or other transports. It is a zero-cost feature since the transport has to have this code internally anyway, and exporting it may even improve the structure of transport impls.

**Comment by pgarneau** [comment]
We're developing a Kafka implementation internally and we want to use the CloudEvents format, but currently can't because there's no easy way to simply translate (bytes, string, etc) into a an Event object and manipulate it. We don't want to use the HTTP, Pubsub, etc receivers since we have our own for Kafka

**Comment by n3wscott** [comment]
@pgarneau you can use the codecs directly if you choose.

**Comment by n3wscott** [comment]
@alanconway I commented on #141, I think it is the correct direction with some tweaks for golang and to match the style of the project.

**Comment by pgarneau** [comment]
@n3wscott Thanks! I'll give it a try and see where it takes me.

**Comment by n3wscott** [comment]
@pgarneau if you want to add kafka transport to this sdk, that would be really awesome.

**Comment by slinkydeveloper** [comment]
Done in sdk v2
