### ISSUE TITLE
Adjust v.03 implementation to make use of canonical string representation

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/sdk-go#143]
According to https://github.com/cloudevents/spec/pull/432 attribute values must be encoded in their canonical string representation. The SDK so far follows the old approach of [JSON encoding ](https://github.com/cloudevents/sdk-go/blob/56931988abe3adf6792b5c6e575ee5f573e9ccbc/pkg/cloudevents/transport/amqp/codec.go#L126) the value.

**Comment by n3wscott** [comment]
I never agreed with the spec and never implemented the json encoded quoted strings. I _think_ I am using canonical string values in headers. But please point out where this SDK is not. I do want to follow the spec as closely as possible (when it is correct 😆)

**Comment by deissnerk** [comment]
There was a link to an example in my text above. It's in the toHeaders() function. Basically, for extensions `encoded, err := json.Marshal(v)`is called.

**Comment by n3wscott** [comment]
Ah, yes that is a bug. 

Want to fix it? :D 

I will get to it eventually if not.

**Comment by diegomarangoni** [comment]
I could help with that, I just a little bit lost. Any suggestion how to implement @n3wscott ?

**Comment by diegomarangoni** [comment]
I opened a PR with a fix for that...
Not sure if is the best way to implement it
https://github.com/cloudevents/sdk-go/pull/184

**Comment by n3wscott** [comment]
Looks like @diegomarangoni fixed this. Closing
