### ISSUE TITLE
Additions to API for transport.Message and the transport API

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#144]
This proposal is based on my old prototype at https://godoc.org/github.com/alanconway/lightning/pkg/lightning#Message

```
package transport
type Message interface {
    // CloudEventsVersion returns the version of the CloudEvent.
    CloudEventsVersion() string

     // Event decodes and returns the event.
     // May consume event data, can only be called once.
    Event() (Event, error)
   
    // Structured returns a complete encoded event as an io.Reader and
    // the media-type describing the encoding (e.g. "application/cloudEvents+json")
    // if the message contains a structured encoding. 
    // If  not it returns (nil, "")
    Structured() (data io.Reader, mediaType string)
}

// Receiver for Message
type MReceiver interface {
    Receive(context.Context, Message) error
}

// Transport for Message
type MTransport interface {
    Send(context.Context, Message) error

    SetReceiver(MReceiver)
    StartReceiver(context.Context) error
}

```

Justification:

Having Event() on Message() is more type safe and allows a Message to be decoded without knowing what the original transport.Codec was. I would still keep Decode on Codec for symmetry and implement on in terms of the other. 

Structured() is an optimization for flowing structured messages thru a system without decoding them at all until it is required - that is one of the goals of the structured mapping in the cloudevents spec. It's optional - a transport can just implement Event().

I wrote it as a io.Reader, following the net.http pattern elsewhere we're using []byte so it seems there's been a decision to always read complete events into memory. We could use []byte for the Structured() call as well if we have definitely ruled out the notion of ever streaming large events.

MTransport: the transport should really be about Message not Event. Message is an abstract transport message - it can be exchanged *between different transports*.  E.g. streaming structured messages thru a bridge only works if I can pass Message from one transport to another *without* pulling out an Event.

QoS is another case where we may need to enhance the Message API - I haven't finally decided if it's necessary to have an explicit hand-over of responsibility between transports or if we can just allow goroutines to block till things are safe.

**Comment by n3wscott** [comment]
You also need to accommodate for binary mode. 

I share the event between transports. Message was intended to be an internal detail of each transport which is why each define their own.

**Comment by alanconway** [comment]
On Fri, Jun 14, 2019 at 1:03 PM Scott Nichols <notifications@github.com>
wrote:

> You also need to accommodate for binary mode.
>

Yes that's exactly why I introduced a common Message interface in lightning

- Event: an unpacked event that the program can examine and modify
- Message: an opaque envelope *containing* and event, in some
transport-specific encoding (binary, structured or some other weirdo
format.)

> I share the event between transports. Message was intended to be an
> internal detail of each transport which is why each define their own.
>
The message implementation is private to the transports, but the ability to
extract an Event from a message is part of the common interface so you can
move events between transports.

My lightning messages allow  you to:
https://godoc.org/github.com/alanconway/lightning/pkg/lightning#Message
1. Extract a structured event as  a mediaType and a byte blob - only works
if the Message actually contains a structured event.
2. Extract an Event - always works, the transport can always decode an
Event no matter how it was encoded.
There's no special Message.Binary event because that's just Message.Event.

The idea is to allow structured messages to passed from one transport to
another without decoding - that optimization is one of the reasons the spec
requires the two different encoding options. Structured is intended for
fast pass-thru with minimal re-encoding. Binary is intended to allow the
transports to have more insight into event metadata for routing or other
purposes.

**Comment by alanconway** [comment]
Duplicate of #162 - better code and examples based on existing cloudevents APIs will be added there.
