### ISSUE TITLE
Problems with coupling in the transport API.

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#145]
Eventing is aimed at de-coupled, asynchronous applications but the CE transpots API has inherited some request-response assumptions from HTTP. I'd like to propose breaking these apart. History shows (repeatedly) that once request-response assumptions get built into a design, they become almost impossible to undo -  even if that wasn't the original  intent. Also the current receiver design forces serialization that may not be desired.

I propose:

type Transport interface {
    Send(context.Context, Message) error
    Receive(context.Context) (Message, Error)
}

NOTES: 

1. There is no notion of a "response event" anywhere. You can have bi-directional event-flows but you cann't "respond" to an event. The cloudevents spec lacks request/response correlation for a reason.

Some transports (HTTP) have request-response semantics and offer the (bizzare) option of sending events as response. This is a Terrible Idea. If you need request/response semantics use HTTP, don't use cloudevents! But if we have to support it, it should be an optional sideline for weirdo non-messaging protocols:

```
interface MessageResponder { Respond(context.Context, Message) error }

m, err := t.Receive(ctx)
if mr, ok := m.(MessageResponder); ok {
    mr.Respond(...)
}
```
2. No serialization constraints: the user can call Receive() in a loop in a single goroutine or process events in parallel any way they want. Unlike net.http handlers, we can't predict whether a given application will want to handle events serially or in parallel .

**Comment by n3wscott** [comment]
The message object is not intended to be shared outside of the transport. The cloudevent.Event object is the shareable object. 

I think this is a question around blocking or non-blocking receiver for the transport.

This is assumed to be blocking: 

```golang
type Transport interface {
  Send(context.Context, Message) error
  Receive(context.Context) (Message, Error)
}
```

But I don't like elevating the transport message out of the transport. I would rather keep the abstraction:

```golang
type Transport interface {
  Send(context.Context, cloudevent.Event) error
  Receive(context.Context) (cloudevent.Event, Error)
}
```

This has some pretty large downsides for implementation, we will have to queue all received events from a transport. And we will have to understand how to drop events if the queue becomes too large. And there is a time based ack/nack problem for transports like AMQP and PubSub.

For this reason I prefer the callback impl. 

I have been making the transports as simple as they need to be and putting fancy features in the thin client. The client could have blocking style calls and then the client gets to implement the buffers and queues, and that code is shared for all transports. But it does it on cloudevents.Event objects, not transport messages.


I think we should break apart point 2 and raise it to the WG. I think it has become the most important issue with regards to the spec and how it is being used. Knative is banking on this notion that you can use cloudevents over http and rely on the reply to inject new events into the eventing mesh.

**Comment by alanconway** [comment]
On Fri, Jun 14, 2019 at 1:14 PM Scott Nichols <notifications@github.com>
wrote:

> The message object is not intended to be shared outside of the transport.
> The cloudevent.Event object is the shareable object.
>
> I think this is a question around blocking or non-blocking receiver for
> the transport.
>
> This is assumed to be blocking:
>
> type Transport interface {
>   Send(context.Context, Message) error
>   Receive(context.Context) (Message, Error)
> }
>
> But I don't like elevating the transport message out of the transport. I
> would rather keep the abstraction:
>
> type Transport interface {
>   Send(context.Context, cloudevent.Event) error
>   Receive(context.Context) (cloudevent.Event, Error)
> }
>
> This has some pretty large downsides for implementation, we will have to
> queue all received events from a transport. And we will have to understand
> how to drop events if the queue becomes too large. And there is a time
> based ack/nack problem for transports like AMQP and PubSub.
>
> For this reason I prefer the callback impl.
>
> I have been making the transports as simple as they need to be and putting
> fancy features in the thin client. The client could have blocking style
> calls and then the client gets to implement the buffers and queues, and
> that code is shared for all transports. But it does it on cloudevents.Event
> objects, not transport messages.
>
> I think we should break apart point 2 and raise it to the WG. I think it
> has become the most important issue with regards to the spec and how it is
> being used. Knative is banking on this notion that you can use cloudevents
> over http and rely on the reply to inject new events into the eventing mesh.
>

The CE library already has a Client API to send and receive Event, it uses
the callback style you prefer. That is the API for "normal application"
developers, they should never touch the transport API except to set up a
client.

The Transport API is for transport implementers and infrastructure
developers (building routers, brokers, channels or the like) . It should
still be as simple as possible but there are different requirements:

- it needs to allow efficient transport-to-transport data flow for things
like event routers.
- it (will eventually) need to deal with issues like acknowledgement and
reliable message transfer between transports.
- it needs to allow efficient integration with pre-existing server
dispatching schemes (avoid imposing serialization/concurrency assumptions.)

Message is a Transport concept, not a Client concept. However there are
things that need to be communicated *between transports*:
- Extracting un-decoded structured events for straight pass-thru between
transports.
- Communicating acknowledgements or "transfer-of-responsibility" for
reliable QoS

None of this appears at the Client level, except that users create a
transport to back their client - the interface to the transport itself is
irrelevant to the client user.

Here's the Message interface from my lightning project - it lacks an
acknowledgement method (used to be called Message.Finish()) as I didn't get
that part fully worked out.
https://godoc.org/github.com/alanconway/lightning/pkg/lightning#Message

**Comment by n3wscott** [comment]
> Message is a Transport concept, not a Client concept. However there are
> things that need to be communicated *between transports*

I disagree on this point. I am using Message to communicate between Transport and Codec. Not Transport to Transport. I am not seeing how this can be done in a way that does not bubble you all the way up to an Event and back down to a Message via the Codec.

**Comment by alanconway** [comment]
Understand your confusion - I need to answer this with code and examples,
will put something together in next couple days.

**Comment by alanconway** [comment]
This issue is covering too much, which is confusing and hard to discuss. Closing it in favour of the following break-down issues:

- Drop cloudevents.EventResponse https://github.com/cloudevents/sdk-go/issues/160
- Suggest blocking Receive vs. callback. https://github.com/cloudevents/sdk-go/issues/161
- Message interface for inter-transport use https://github.com/cloudevents/sdk-go/issues/162
