### ISSUE TITLE
go mod tidy needs more info

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#148]
running `go mod tidy` removes `github.com/gogo/protobuf v1.2.0` from the `go.mod` file.
running `./hack/update-deps.sh` adds `github.com/gogo/protobuf v1.2.0` to the `go.mod` file.

wtf.

The root cause is the module of the project is pointing at the root, and the go code is only the alias file, and the alias file only has http transport. 

I think the correct answer is to add more mod files in the transport directories, because these are optional add-ons. But that answer is pretty trash. 

Anyone know?

**Comment by n3wscott** [comment]
fyi: @thinkerou I think this was the issue you ran into.

**Comment by thinkerou** [comment]
@n3wscott thank your explain.

**Comment by n3wscott** [comment]
@alanconway fixed it!
