### ISSUE TITLE
Can't get extensions with a case-insensitive key

### ISSUE THREAD

**Issue by grantr** [cloudevents/sdk-go#150]
CloudEvents transported with HTTP binary mode have case-insensitive attribute keys due to HTTP headers being case-insensitive, but this isn't always clear to implementers. Compounding the problem is that Go leans hard into case insensitivity and mangles header keys to their Canonical MIME Encoding, so comparing header keys directly after a serialization roundtrip is going to cause pain.

See https://github.com/knative/eventing/blob/master/pkg/broker/receiver.go#L137. This code sets an extension with a lowercase name and expects that lowercase name to still be valid in the `Extensions` map, but Go has already changed its name to something else.

To avoid this problem, sdk-go should very loudly document the `Extensions` map as not suitable for querying, and provide a method for querying extensions in a case-insensitive way. Ideally, the `Extensions` value would implement the same or similar interface as `http.Header`.

/cc @n3wscott

**Comment by n3wscott** [comment]
good idea.
