### ISSUE TITLE
Should we start deprecating versions of the spec? like v0.1

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#156]
Can we start removing v0.1? It is the most divergent of the encodings.

**Comment by n3wscott** [comment]
@markpeek @alanconway

**Comment by n3wscott** [comment]
Ping on this. I am going to make a PR in the next week to remove 0.1 :D

**Comment by n3wscott** [comment]
SAP is using this. Will hold on until I get word they don't dep on it.

**Comment by alanconway** [comment]
I'm fine with deprecation.

**Comment by slinkydeveloper** [comment]
Done in sdk v2
