### ISSUE TITLE
Drop cloudevents.EventResponse

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#160]
TL;DNR: The cloudevents/sdk-go API should follow message-oriented examples (AMQP, MQTT, Kafka) *not* RPC-oriented examples (HTTP, gRPC). That means separate, one-way Send and Receive operations with no implied coupling between sending one event and receiving another (no EventReponse). The only possible result from Send is an error indicating a delivery problem *not* a response containing data from a remote application.

# Details

"An  [event](https://github.com/cloudevents/spec/blob/v0.3/spec.md#event) is a data record expressing an occurrence and its context." It is *not* a request for service, it does not demand any "response". It simply informs the next link in the chain that something has happened.

We already have HTTP RPC in the cloud, what we need from cloudevents is an alternative loosely-coupled event/message-oriented model. The critical difference from RPC is that sending an event does not imply you will receive one, and receiving an event does not make you responsible for sending one. This is the key to "loose" coupling:

*Decoupled/asynchronous processing*: A sender can send events without knowing how *or when* they are processed. A receiver can process an event immediately, store it for later, forward it, generate new events etc. There's no expectation of matching request-response pairs that ties sender and receiver actions together.

*Routability*: events are easily routed, stored and forwarded, multicast or load-balanced by intermediaries between the sender and receiver. Routing RPC is more difficult because.

- you have to construct a "reverse route" to get the response back, dealing with problems like  one-way firewalls, no-longer-connected clients and requests/responses that get held up in queues.
- you have to fabricate exactly one response from 0, 1 or many (multicast) responses.

Of course the async eventing model introduces complexities that don't exist in RPC,  just as concurrent programming introduces complexities that don't exist in sequential programming. We need both.

It's not sufficient to say the EventResponse parameter is "optional". Its existence implies that API users can use it and API implementers should provide it. That's complicates implementations based on message-oriented middleware like AMQP, MQTT or Kafka, and it encourages API users to view cloudevents as a funny API for HTTP - which makes cloudevents useless, since we already have HTTP.

If there are some strong use cases for an RPC-like exchange of events then they should be implemented using standard HTTP RCP and standard HTTP APIs. The cloudevents APIs should be reserved for event-oriented use cases where we don't want to assume RPC-semantics, or  require implementations to support them.

**Comment by n3wscott** [comment]
How do you suggest implementing filter functions with http and cloudevents?

**Comment by n3wscott** [comment]
Knative uses this use case extensively: 

```producer --> middleware --> invoker --> filter``` 

```(filter function response) ==> invoker --> consumer```

`==>` is the http resp from the original request from the invoker.

**Comment by alanconway** [comment]
So this seems like a convoluted way to say:

producer --> middleware --> invoker --> filter -> consumer

I guess the issue is lack of connectivity and/or addressing information - the filter isn't connected to the consumer or can't tell which consumer to forward to, so we have this funny return loop back to the invoker.

Lemme have a think about this.

**Comment by n3wscott** [comment]
> the filter isn't connected to the consumer or can't tell which consumer to forward to, so we have this funny return loop back to the invoker.

exactly...

**Comment by alanconway** [comment]
> > the filter isn't connected to the consumer or can't tell which consumer to forward to, so we have this funny return loop back to the invoker.
> 
> exactly...

AMQP uses reply-to and correlation-id properties to optionally indicate where to send a reply
We can't do that since Event has no equivalents, and probably shouldn't given it's design goals.
If the use case is already embedded we need to support it, so  I suggest:

```
type Sender interface {
	Send(ctx context.Context, m Message) error
}

type SendReceiver interface {
       Sender
	// SendReceive indicates interest in a response event.
	// Call the returned Receiver.Receive() to receive it.
        SendReceive(ctx context.Context, m Message) (Receiver, error)
}
````

All transports implement Sender, Senders that allow responses can be cast to SendReceiver

**Comment by alanconway** [comment]
Most of this already dealt with by #226, the rest is a duplicate of #227. Closing
