### ISSUE TITLE
Suggest blocking Receive vs. callback.

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#161]
The transport.Transport and client.Client APIs use a callback model for receiving events. This is modeled on net.http, which is motivated by the fact that HTTP is an RPC protocol.

As argued in #160 eventing is different.  Send and Receive are more like io.Writer.Write() and io.Reader.Read() - independent operations with a one-way data flow and only an ok/error outcome as result. The motivation for callbacks does not apply.

The models are equivalent: it is easy to implement the callback model in terms of the blocking model (see below), the reverse is harder. The blocking model is more familiar (io.File, net.Conn, Unix fds etc.) The only reason anyone ever uses the more complex Unix callback models (epoll, kqueue, iocp) is because Unix lacks portable, efficient concurrent dispatch, which Go provides.

**Comment by n3wscott** [comment]
I think you have convinced me that this will work out and the client can still paper over the fact that it wants to do callbacks. 👍

**Comment by alanconway** [comment]
Fixed by #164
