### ISSUE TITLE
Message interface for inter-transport use.

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#162]
Right now the Message interface  can't be used without casting to a transport-specific interface. Its only operation (GetVersion) is useless without additional knowledge about the transport-specific implementation, from which you could just as well get the version directly.

Propose an enhanced Message interface that can be used independently of the transport that created it, in particular as a go-between when forwarding messages from one transport to another.

In particular this solves the following problems that can't be solved with the existing API:

- forward structured event encodings *without decoding* ; provided both transports are happy with the encoding format and don't need to validate or inspect the content. The resulting performance benefits are the main (only?) reason for using structured over binary bindings.
- negotiate reliable qualities of service between different transports with similar QoS levesl (at-most-once, at-least-once, exactly-once) Although each transport can use its own mechanisms to ensure the QoS there is a need to hand-over responsibility between the transports, else messages can be lost if the process doing the forwarding crashes.

Code and examples are nearly complete - coming soon as  PR.

**Comment by alanconway** [comment]
Code and examples in PR #164. The idea is not to push this PR but to use it to focus discussion, we will need to agree on how/if to integrate the various ideas into the main transport package.

**Comment by n3wscott** [comment]
When I was writing this originally I had never thought to pass a transport.Message to any other transport because the impl of the Message object is specific to a transport, and created after passing an Event through a Codec. The interface allows a codec to talk to a transport without being aware for the most part.

**Comment by alanconway** [comment]
> When I was writing this originally I had never thought to pass a transport.Message to any other transport because the impl of the Message object is specific to a transport, and created after passing an Event through a Codec. The interface allows a codec to talk to a transport without being aware for the most part.

Yep, this proposal is to augment the interface so they become useful between transports. The codec still makes sense as a separate entity for users that want to go `Event -> http.Request` or `amqp.Message -> Event` and use their own http or amqp client/server code rather than the Transport/Sender/Receiver we provide.

**Comment by alanconway** [comment]
Fixed by #164
