### ISSUE TITLE
transport eat exact err message which server response

### ISSUE THREAD

**Issue by luodw** [cloudevents/sdk-go#166]
we use cloudevents/sdk-go to send and receive event，when server response a err, for example 404 or 500 with some message， the client with sdk-go can not get err message, only get message such as "error sending cloudevent: 500 Internal Server Error". 

I  found some code here [https://github.com/cloudevents/sdk-go/blob/master/pkg/cloudevents/transport/http/transport.go#L229](https://github.com/cloudevents/sdk-go/blob/master/pkg/cloudevents/transport/http/transport.go#L229)

this is hard to debug when only get 404 or  500, so there is other way to get exact err message?

**Comment by n3wscott** [comment]
You can pull the http transport context out of the context.Context object and get the full details. The API had to be common across many transports and most do not support these kinds of features, so I hooked it in a different way.

**Comment by n3wscott** [comment]
Use the `HTTPTransportContextFrom` method: https://github.com/cloudevents/sdk-go/blob/3eb440c338c784a56b16c9785d872fe8b0ed379f/alias.go#L134 and pass in the context that you are given in your Receive method. If the transport is HTTP then it will be populated with an `http.TransportContext`.

**Comment by n3wscott** [comment]
I think this is solved with the above feature.

Please reopen if not.

**Comment by luodw** [comment]
I am sorry to forget response, I have got it, thank you.
