### ISSUE TITLE
Improved AMQP transport

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#180]
Required features:
- Refactor based on transport/x API - https://github.com/cloudevents/sdk-go/pull/164
- Configuration: client and sever modes (both sides), named links, anonymous relay.
- Delivery QoS: 0 (unreliable) and 1 (at-least-once)
- Codec: Event/AMQP translation for direct AMQP applications.

Nice-to-have (for this iteration):
- Security config: user/pass, SASL, TLS certificates.
- Request-response support (depends on https://github.com/cloudevents/sdk-go/issues/160)

Non-goals  (for this iteration):
- QoS 2 (exactly-once)
- Transactions

**Comment by alanconway** [comment]
@n3wscott I'm thinking of renaming the transport/x package as pkg/message. That avoids clash with existing use  or "transport", fits well with ce spec use of "message" and reads pretty well in code as in "message.Sender", "message.Receiver". message.Message stutters a little but makes sense. What do you think?

**Comment by n3wscott** [comment]
sounds good to me!
-Scott

**Comment by alanconway** [comment]
@n3wscott existing AMQP codec uses string for timestamps and json-encodes all extensions - that doesn't match what it says in https://github.com/cloudevents/spec/blob/master/amqp-format.md which says to use the corresponding native AMQP types (timestamp, map etc.). OK if I fix, or am I missing something?

**Comment by alanconway** [comment]
Switched package x name from "message" to "binding", it seemed a little odd in use, the package provides more than just the message.

**Comment by alanconway** [comment]
Split out #226 for generic binding framework.
