### ISSUE TITLE
Remove panicky Event wrapper methods

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#182]
Event provides a set of trivial wrapper methods that call a corresponding e.Context Get/Set method and panic if it returns a non-nil error.I suggest these wrapper methods  be removed, they add  nothing and create a dangerous point of confusion for the API user: it is normal to assume that a simple Get/Set method with no error return is safe to call, it is very abnormal for such a method to crash the program if it gets invalid arguments. 

Methods that panic should be clearly documented and it should be easy for the caller to establish the pre-conditions for a safe call  (e.g. a pointer is not nil) - that isn't the case here e.g. how should the caller know the set of allowed version for SetSpecVersion() in advance of calling it, as this set changes with new versions of the cloudevents library?

**Comment by alanconway** [comment]
I understand that. The problem is that

a) they are redundant, you can just say event.Context.SetBlah instead of event.SetBlah.
b) they panic instead of returning an error

The panic is the bigger problem, it is not the normal way to indicate a runtime error in Go. Programmers who see functions like cloudevents.New() or Event.SetSpecVersion() with no error return value are likely to assume they always work (setters and constructors are often error-free) so they will be surprised when their application crashes. Handling panics is quite different from normal error handling so these methods are awkward to use safely.

**Comment by n3wscott** [comment]
a) they adapt the old field names to the new field names so the encoders do not need to understand the versions, so they are not 100% redundant. They also help convert types from strings to strongtypes.

b) you can recover if you really want to and 99% of the time this is what the user wants to do because error checking all the setters is a bummer.

**Comment by alanconway** [comment]
Fair enough, but the API comments need to be clear about the panic. It's
natural to assume that what looks like a simple Set function and returns no
error is a non-failing operation.

Also if New() and SetVersion() can panic on an invalid version string, then
the API needs to provide a safe way to determine what is a valid version
string. The set of valid versions changes with new releases of the library.
It's OK to panic if the (documented!) preconditions of the API are not met
- but there has to be a non-panic way to establish those preconditions.

**Comment by n3wscott** [comment]
We removed these now.
