### ISSUE TITLE
Sending an event with data from an io.Reader over HTTP requires two extra buffers

### ISSUE THREAD

**Issue by spencer-p** [cloudevents/sdk-go#186]
If you have data in an `io.Reader` and would like to send it as a Cloud Event with the HTTP transport, it would be most efficient to use the reader as the HTTP request body. However, the API currently requires the caller to first buffer their `io.Reader` to a byte array and set it as the data; then the `http/transport.Message.copyOut` method creates another buffer of the same data.

I understand that we're trying to not modify the caller's copy of their data. However, I think eliminating extra buffering will be more useful to developers than being able to reuse the event payload. Developers that need to reuse the payload can always buffer it themselves, but the current API enforces this buffering (twice).

Sidenote - the `http/transport.Message.copyOut` implementation uses `append` to create a copy, which IIRC costs more allocations than the `copy` method ([godoc](https://golang.org/pkg/builtin/#copy)).

**Comment by slinkydeveloper** [comment]
Addressed by the new bindings api
