### ISSUE TITLE
Right now ParseTimestamp() doesn't return an error. It's debatable on what to do if there is a bad time being presented whether to fail entirely or, as in the case, silently drop.

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#188]
https://github.com/cloudevents/sdk-go/pull/187#discussion_r324311954

Right now ParseTimestamp() doesn't return an error. It's debatable on what to do if there is a bad time being presented whether to fail entirely or, as in the case, silently drop. Perhaps open an issue?

_Originally posted by @markpeek in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzE3NDE2NDI5/pull_requests/unread_timeline_

**Comment by n3wscott** [comment]
I am moving this to SDKv2

**Comment by slinkydeveloper** [comment]
In SDK v2 returns an error
