### ISSUE TITLE
Implement Distributed Tracing extension

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#199]
Ref: https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md

**Comment by meetme2meat** [comment]
@n3wscott  All that is needed here is to set the `traceparent` and `tracestate` attribute, correct?

Also in reference to W3C TC, only  Dynatrace has implemented it. For Zipkin and Jaeger, the support is still not out.

**Comment by ian-mi** [comment]
#303 only defines the extension, trace propagation still needs to be implemented.

**Comment by n3wscott** [comment]
Ok we will revisit more integration.

**Comment by ian-mi** [comment]
This should now be fixed by #309
