### ISSUE TITLE
Numeric strings are parsed as integers

### ISSUE THREAD

**Issue by aaron-lerner** [cloudevents/sdk-go#209]
I have an event source with CE override extensions like:
```
{"key": "4002909746823859279"}
```

However, when an event is actually received, the same field inside `event.Extensions()` now looks like:
```
{"key": "4.002909746823859e+18"}
```

**Comment by n3wscott** [comment]
Interesting. We will make a test to repo and fix. Sorry!!

**Comment by n3wscott** [comment]
Unable to repo this in a test. Please reopen if you have a repro case.
