### ISSUE TITLE
MarshalJSON modifies the Event

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#217]
MarhalJSON sets the event's datacontenttype to app/json if it is nil.

This is unnecessary: app/json is implied when an event is in JSON format, so there's no need to add it explicitly.

It is also incorrect: In general json.Marshal() should not modify the object being marshalled as a side-effect. Changing the datacontent from nil as a side effect will cause problems if the event is marshalled to  a different format later.

**Comment by n3wscott** [comment]
I did this because the media type is how the decoder is selected. Without that, it defaults to json.

**Comment by alanconway** [comment]
So here's my take:

cloudevents.Event is a binding-neutral representation of the event. It has no ties to JSON, HTML or the like. The same Event might be encoded multiple times in by different bindings, encoding it once should  not have side-effects that will change the way it gets encoded later.

Context.Extension attribute values are stored using the Go types defined in package types, or canonical CE strings. These are independent of JSON and the rest.

Event.Data is described by DataContentType, there are 2 cases:

1. DataContentType is a non-empty string: event.Data MUST be []byte or string, and must be interpreted as a byte sequence conforming to the DataContentType media-type.

2. DataContentType is nil or "": event.Data MUST be convertible to one of the CE types from package types and MUST be interpreted as that type.

So for JSON marshalling: if there is a DataContentType, we copy the Data bytes as base64 and set the JSON datacontenttype attribute. If there is no DataContentType, we leave the JSON datacontenttype unset (which implies JSON format since we are constructing a JSON event) and we JSON-encode the DATA value using the usual rules.

An event with no DataContentType should round-trip through any binding and come back the same: with no DataContentType and a Data value that is one of the CE types. Each binding must have some default encoding that it uses when DataContentType is unset. E.g. AMQP has it's own type system. 

NOTE: The default encoding is going to be lossy - both JSON and AMQP have no special representation for URI or URI-Reference so those will come back as string. I don't think we need to worry about it though, as the default encoding is unlikely to be used for anything but string and []byte.  Personally I would encourage people not to use it at all, an explicit contenttype and a bag of bytes is much less likely to wind up down a rathole if events get routed/transformed and the like.

**Comment by deissnerk** [comment]
>DataContentType is nil or "": event.Data MUST be convertible to one of the CE types from package types and MUST be interpreted as that type.

I think that is not true. `data` is [not limited by the CE type system.](https://github.com/cloudevents/spec/blob/master/spec.md#datacontenttype):
>When this attribute [datacontenttype] is omitted, data simply follows the event format's encoding rules. For the JSON event format, the data value can therefore be a JSON object, array, or value.

Consequently a bridge that transcodes from JSON format to AMQP format would need to convert an arbitrary JSON Value into an arbitrary AMQP Value, which actually scares me.

**Comment by alanconway** [comment]
@deissnerk agreed that data is not limited to the CE type system *if* there is a datacontentype that describes how it is encoded. The absence of a datacontenttype implies that the event data is encoded using the default encoding rules for the binding. Those default rules are *only* defined for CE types. So: if there is a content type, we know how to encode/decode (or we can forward to someone who does) if there is no content type we are restricted to the CE types and each binding has it's own non-standard way to encode and decode those so again, we're OK.
