### ISSUE TITLE
Rework client API in Sender/Receiver style similar to binding package

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#228]
The client will still Send/Receive Event (not Message) but following the Sender/Receiver pattern.
Note this should include the resolution of https://github.com/cloudevents/sdk-go/issues/227

Events are distinct from HTTP: Events support *stream* style communication - one way streams of events. HTTP supports RPC-style communicaiton: each request gets a response. Both are important paradigms - HTTP already covers RPC well;  the eventing API and implementation should be focussed on one-way streams of events. 

Even if eventing is often implemented over HTTP, the optimal way to use HTTP for carrying events is different from using it to carrying end-to-end correlated requests and responses, especially with the extra flexibility of HTTP2.

**Comment by n3wscott** [comment]
We did this! Woot! Implemented `client.Send` and `client.Request`
