### ISSUE TITLE
how to get response error?

### ISSUE THREAD

**Issue by qianlnk** [cloudevents/sdk-go#249]
when I return an error in func receiver as:

resp.Error(23, "error message")

but can't get error when send

why send func not return EventResponse?

**Comment by n3wscott** [comment]
It depends on the transport you select to outline what is allowed. For example, HTTP allows response but AMQP does not (except for ack/nack). Responses are not well implemented in the current SDK for things other than HTTP unfortunately. We do have a SDKv2 in the works that makes  this interaction more clear. 

Can you share a snip of code that you are having issues with? Perhaps I can help debug.

**Comment by n3wscott** [comment]
Closing from inactivity
