### ISSUE TITLE
Does SetID() work?

### ISSUE THREAD

**Issue by timbray** [cloudevents/sdk-go#251]
I constructed an event with an explicit WithID value but it looks to me like the SDK generated a new ID anyhow. Is this expected?

**Comment by n3wscott** [comment]
Do you mean you used `cloudevents.WithUUIDs` when generating the client? This will add a `id` _if_ `id` is not set in the event.

For example, this is used in `NewDefaultClient`:

```go
func NewDefault() (Client, error) {
	t, err := http.New(http.WithBinaryEncoding())
	if err != nil {
		return nil, err
	}
	c, err := New(t, WithTimeNow(), WithUUIDs())
	if err != nil {
		return nil, err
	}
	return c, nil
}
```

you should be able to do the following:

```go
event := cloudevents.NewEvent("1.0")
event.SetID("foo-bar")
...
c.Send(event)
```

And then regardless of the client being set with `WithUUIDs`, "foo-bar" should be sent out.

**Comment by timbray** [comment]
OK, yes, the "1.0" argument on `NewEvent()` seems to have made the problem go away, thanks.
