### ISSUE TITLE
Support for NATS Queue Subscriptions

### ISSUE THREAD

**Issue by dan-j** [cloudevents/sdk-go#258]
Not properly thought about a solution for this yet, but is it something you'd accept a PR for?

The appropriate docs can be found here: https://docs.nats.io/developing-with-nats/receiving/queues

In essence, a queue subscription tells NATS to load balance messages to multiple subscribers. Whereas the current NATS Transport only allows traditional subscribers, if two instances connect with the same configuration, messages will be sent to both clients.

Like I said, I haven't really thought through how this would be implemented, but willing to have a discussion and contribute a PR 😄

**Comment by n3wscott** [comment]
I wrote the current impl not being a current NATS user. PLEASE help me make it better! 👍

**Comment by dan-j** [comment]
I'll need this functionality in a few weeks, so I will either get round to it then, or might try and whip something up sooner if I get some free time.

**Comment by rob0t7** [comment]
Funny that this is exactly the same functionality that I also need to ensure that the message is not processed by more than 1 worker in the same group. 

@dan-j any progress or PR on this issue?

**Comment by dan-j** [comment]
I have implemented the same thing for NATS Streaming (aka STAN) in PR #322, I need to add tests and examples before it can get merged, then I'll be back to focus on NATS. I'll more than likely address this at the same time as #316. 

I probably won't get to any NATS stuff until w/c 30th though. If you need it more urgently, you can see how I've implemented it in #322 and follow the same pattern?

**Comment by ripienaar** [comment]
As an aside we (NATS) will in the next few months release our next gen streaming platform called JetStream, I'll revist here then to add support for that when ready

**Comment by dan-j** [comment]
Fixed by #415

**Comment by zhaojizhuang** [comment]
> As an aside we (NATS) will in the next few months release our next gen streaming platform called JetStream, I'll revist here then to add support for that when ready

@ripienaar Is there any progress in support for JetStream

**Comment by ripienaar** [comment]
Jetstream is out and released but have not had a time to revisit integrations
