### ISSUE TITLE
binding to transfer binary events without allocating an intermediate 

### ISSUE THREAD

**Issue by alanconway** [cloudevents/sdk-go#262]
The current binding.Message.Event() API creates an intermediate Event object which then must be encoded to be sent by a Sender. Provide an additional API that allows binary events to be transferred without an intermediate Event data structure (analogous to the way Message.Structured() avoids intermediate data structures for structured messages.)

Idea provided by @slinkydeveloper 
Initial proposal #263

**Comment by alanconway** [comment]
Proposal in #263

**Comment by slinkydeveloper** [comment]
I'm on it
