### ISSUE TITLE
0.10.1 tag

### ISSUE THREAD

**Issue by ianpartridge** [cloudevents/sdk-go#264]
Version `0.10.1` was tagged without a `v` prefix, unlike previous versions e.g. `v0.10.0`.

Was this intentional? https://golang.org/cmd/go/#hdr-Module_queries

**Comment by n3wscott** [comment]
Sorry!

**Comment by n3wscott** [comment]
Fixed https://github.com/cloudevents/sdk-go/releases/tag/v0.10.1
