### ISSUE TITLE
Improve NATS transport

### ISSUE THREAD

**Issue by ripienaar** [cloudevents/sdk-go#268]
Today the NATS transport is very limited - no ability to use TLS, credentials, users, passwords etc. There's a whole pile of features one might want in real world.

So rather than try to map all the many nats options 1:1 here, would you object to me adding a option to the transport where a fully configured NATS connection can be passed in as an option? This way users can handle all the setup, authentication, tls etc on their own and pass in a suitabily prepared connector?

We can add commonly used options into the transport but honestly it'll be forever going round in circles that way, passing in a connection is path of least resistance and something people do elsewhere in the NATS eco system

**Comment by ripienaar** [comment]
The proposed change is in a WIP PR https://github.com/cloudevents/sdk-go/pull/269/files

**Comment by ripienaar** [comment]
I also added a little helper so one can pass in any nats option in stead of the extra work to pre-make a nats connection.

**Comment by ripienaar** [comment]
Have simplified this down to just taking nats options and not a prepared connection.

**Comment by ripienaar** [comment]
this should tick off https://github.com/cloudevents/sdk-go/issues/62

**Comment by n3wscott** [comment]
Is this closable now?

**Comment by ripienaar** [comment]
yup@
