### ISSUE TITLE
Direct use of Encoders should be possible

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/sdk-go#286]
Both existing bindings, HTTP and AMQP, do not export their Encoders. So they can only be instantiated within their packages. The only place I found, was the according `Send()` method of the Senders. How can I use the Encoders directly, if I prefer to handle the transport directly? In HTTP I might want to use something else then POST, or I might want to implement a special retry logic or react to return codes which do not seem to be exposed.

**Comment by slinkydeveloper** [comment]
This is related to the ongoing discussion on fanout implementation: #282, #283, #281

I'm prone to make the encoders public and exposing the logic to use them (which resides now in methods like https://github.com/cloudevents/sdk-go/blob/master/pkg/bindings/http/sender.go#L56), but this heavily depends on how we want to support multi dispatch of the same message.

**Comment by n3wscott** [comment]
I agree this should be possible. We will make it so.
