### ISSUE TITLE
It is not possible to expose routes by cloud events http client

### ISSUE THREAD

**Issue by andreiac-silva** [cloudevents/sdk-go#288]
I've been using the receiver (started by StarterReceiver) feature from the cloud events package. Once a cloud event client is created, it is not possible to connect other clients in the application port. On the other hand, my service requires to expose some other URIs which are not related to cloud events, in the same port. 

Is there some way to use the mux client of the library to create routes avoiding pass by ServeHTTP implemented by Transport?

**Comment by n3wscott** [comment]
YES! Here is an example of using the http mux server to host a metrics endoint off the same port as the cloudevents sdk: https://github.com/cloudevents/sdk-go/blob/a1c7a759c034d9289981dd8ca42ff3663842a8a6/cmd/samples/stats/main.go

Where the current sdk does not help (for the client wrapping) is if you want to use something else like gorilla, and if that is a need we should talk about it and we can figure out a way to make it work;.

**Comment by n3wscott** [comment]
@andreiac-silva Please re-open if this did not solve your issue. Thanks for the question!
