### ISSUE TITLE
bindings HTTP Message should allow to reply with an Event

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#295]
The HTTP Message should expose a functionality to reply to a specific event

**Comment by slinkydeveloper** [comment]
Is this a special case that only HTTP Message should allow or should we generalize it to all bindings (like putting it in `Finish`)? WDYT @alanconway @n3wscott ?

**Comment by n3wscott** [comment]
There was an idea to have two styles: A receiver and a responder. 

I think we should have a meeting to talk about v2 stuff to get on the same page and make a vision. I have something started... Will be in touch.

**Comment by slinkydeveloper** [comment]
Ok cool, let me know

**Comment by alanconway** [comment]
I might jump in on that meeting - I'm not working on this directly anymore
but I have strong opinions :)

**Comment by slinkydeveloper** [comment]
Solved adding a `Requester` and `Responder` interface, without working directly on `Message`
