### ISSUE TITLE
Kafka Binding & Kafka Transport

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#298]
Implement a Kafka binding and relative transport

**Comment by matzew** [comment]
Do we have any thoughts about clients, that can be used ? 

* Shopify/sarama
* confluent-kafka-go

I think it would be good if this "client", for kafka could be than also used inside of Knative components, that currently already deal with Kafka AND CloudEvents.

**Comment by slinkydeveloper** [comment]
> Do we have any thoughts about clients, that can be used ?

I think that, in this project, we should use an 100% go client (maybe sarama?), without any c dependencies.
I had a discussion with @n3wscott about the fact that we should keep abstract the encoding part from the `Sender` and `Receiver` implementations. This allows people to reuse encoders and write their own send and receive logic, with the client they want and implementing the optimizations they want. At the same time, we don't need in this client to cover complex use cases, causing leaky abstractions (like event response status code we have now that makes sense only for HTTP)

**Comment by n3wscott** [comment]
One of the long term goals is that we can allow an integrator to choose one of a few integrations with popular client libs, so if one of them happens to be a C dep, maybe? or at least make it possible to wrap that lib with our api externally from this repo to allow folks to use the lib they have investment with.

**Comment by davyodom** [comment]
There are so many different ways to use these different clients from a code perspective, optimizing for different use cases and providing different qualities of service.  E.g. frequency of offset commit, async/sync producing, etc.  Is it part of the scope of the cloudevents sdk is to try to cover all of those? 

IMHO, makes sense to keep the kafka protocol binding / encoding part which is directly a part of the cloud events spec distinct and easily useable.  Also fine to have an opinionated basic implementation which is useable out of the box, but expect people to use their own preferred clients with their patterns and configuration of choice.

**Comment by slinkydeveloper** [comment]
This library looks interesting too: https://github.com/segmentio/kafka-go

**Comment by aslom** [comment]
There is more libraries in Go: https://cwiki.apache.org/confluence/display/KAFKA/Clients#Clients-Go(AKAgolang)

I wish there was detailed list of required features that client must support and have that listed for easy comparing, especially comparing to Apache Java client version.

**Comment by slinkydeveloper** [comment]
@aslom Unfortunately that list is old and incomplete, most of these listed libraries are abandoned. AFAIK the only maintained libraries out there are:

* https://github.com/Shopify/sarama
* https://github.com/confluentinc/confluent-kafka-go
* https://github.com/segmentio/kafka-go

**Comment by slinkydeveloper** [comment]
Kafka binding implemented in https://github.com/cloudevents/sdk-go/pull/314
