### ISSUE TITLE
BindingTransport does not allow transport.Converter to be used

### ISSUE THREAD

**Issue by dan-j** [cloudevents/sdk-go#315]
Spoken to @slinkydeveloper on Slack about this. It turns out that migrating transports to use the new bindings API isn't compatible yet since there's no way to assign a `transport.Converter` to the `binding.BindingTransport` struct

Changes that need making:

- Add a `Converter transport.Converter` field to the `binding.BindingTransport` struct
- Update the `SetConverter` and `HasConverter` functions
- Inside `BindingTransport.handle()`, use the encoding returned from `ToEvent` and if it's "EncodingUnknown" then use the `Converter` (if it's set)

**Comment by slinkydeveloper** [comment]
Is this one still valid @n3wscott ?

**Comment by dan-j** [comment]
No this isn't valid anymore, I'll close
