### ISSUE TITLE
NATS transport, unable to reuse connections for multiple subscriptions

### ISSUE THREAD

**Issue by dan-j** [cloudevents/sdk-go#316]
If an application wishes to subscribe to multiple NATS subjects it must create separate `Transport`s which means creating new connections. 

This could be mitigated in two ways:

1. Change the signature to `nats.New(conn *nats.Conn, queue string, opts ...Option) ...`. This would be a breaking change so would have to be in the v2 release
2. Add a `WithConn(conn *nats.Conn) Option` option which if set doesn't call `t.connect()` in the constructor, this isn't a breaking change, but makes the API a little less clear.

Alternative options that I am not in favour of:
- Create the struct manually - there's a fair bit of setup in the constructor
- Use the constructor but then do `t.Conn = anotherConn` - this adds overhead of starting multiple connections unnecessarily.

**Comment by n3wscott** [comment]
I did not know much about nats when I wrote the original version... So if you have insight please do come help.

**Comment by dan-j** [comment]
This should follow the similar pattern to kafka (and STAN when it's merged) protocol where we we have `New` and `NewFromConn` constructors

**Comment by slinkydeveloper** [comment]
@dan-j Are you willing to contribute for it?

**Comment by dan-j** [comment]
Yeah, will be after STAN gets tests/examples and is merged though.

**Comment by dan-j** [comment]
Fixed by #415
