### ISSUE TITLE
Prune v 0.1 & v 0.2

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#330]
Prune Cloudevents versions 0.1 & 0.2

## Bindings specific

This includes removing the "hack" to extract the event version in https://github.com/cloudevents/sdk-go/blob/master/pkg/binding/spec/spec.go#L61 & https://github.com/cloudevents/sdk-go/blob/master/pkg/binding/spec/spec.go#L68, which now could be simplified to:

```
func (vs *Versions) SpecVersionName() string
```

And the caller just does:

```
if v, err := versions.Version(messageHeaders[versions.SpecVersionName()]); err == nil {
  // I have a spec version
}
```

**Comment by n3wscott** [comment]
0.1 is now gone with #337 

I will work on removing 0.2 today.
