### ISSUE TITLE
binding.EventMessage support for different formats in Structured method

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#345]
`binding.EventMessage` now defaults to `JSON` to convert the `EventMessage` back to an `io.Reader`. We should add support for all formats registered in `binding.format` package through the provided context.

Ref: https://github.com/cloudevents/sdk-go/blob/master/pkg/binding/event_message.go#L26

**Comment by n3wscott** [comment]
are you using or aware of the datacodec?

**Comment by slinkydeveloper** [comment]
Yes, `format` clones some functionalities of datacodec, we should find a way to fit them together
