### ISSUE TITLE
Make a channel based protocol binding.

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/sdk-go#417]
It would be nice if we could send events between objects via channels in go as a client interaction.

**Comment by slinkydeveloper** [comment]
Somehow this already exists :smile: https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/test/chan_receiver.go

**Comment by slinkydeveloper** [comment]
We just need to make it less "internal" probably

**Comment by n3wscott** [comment]
oh yeah...fml I just found it.

```
// ChanSender implements Sender by sending on a channel.
type ChanSender chan<- Message

// ChanReceiver implements Receiver by receiving from a channel.
type ChanReceiver <-chan Message
```
