### ISSUE TITLE
Add support for retries

### ISSUE THREAD

**Issue by lionelvillard** [cloudevents/sdk-go#423]
When an event failed to be sent the SDK should retry sending it. There should be a way to configure how many times to retry before giving up, the backoff policy (eg `linear`, `exponential`, etc..) and associated parameters (eg. backoff delay)

**Comment by lionelvillard** [comment]
I can give shot at this one.

**Comment by lionelvillard** [comment]
Here my current thoughts on how to implement this:
- add a new retry client (`NewRetried`) for wrapping clients that don't support retrying natively.
- add `ContextWithRetry(max, backoff)`
- update default client to use `NewRetried`

The sarama client supports retries natively but only support configuration at the client level, not at the producer level. In that case `ContextWithRetry` will be ignored. 

I haven't looked at the other protocols but I'm guessing the general idea is the same.

@n3wscott @slinkydeveloper comments?

**Comment by n3wscott** [comment]
I think this is an interesting option for http. I would implement it in this method: https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/http/protocol.go#L102

you could make a little helper class that replaces:

```go
	resp, err := p.Client.Do(req)
	if err != nil {
		return nil, protocol.NewReceipt(false, "%w", err)
	}

	var result protocol.Result
	if resp.StatusCode/100 == 2 {
		result = protocol.ResultACK
	} else {
		result = protocol.ResultNACK
	}
```

And normal it would just try once.

And if you find `ContextWithRetry(max, backoff)`, implement a retry and backoff sender.

The last thing I would do is make a small report about how many times it took to send in the result.

I would extend the HTTPResult as HTTPRetriesResult that lets you report things like how many retries and how long it took and the response code of the final try (plus wrap in ACK or NACK)

**Comment by n3wscott** [comment]
helper class or method.

**Comment by lionelvillard** [comment]
I guess we can start with HTTP and generalize later on.
