### ISSUE TITLE
Publish separate go module for each protocol

### ISSUE THREAD

**Issue by tamalsaha** [cloudevents/sdk-go#450]
We would like to see separate go modules published for  https://github.com/cloudevents/sdk-go/tree/master/v2/protocol packages. This will help us avoid taking on dependencies on protocol libraries we are not using.

**Comment by n3wscott** [comment]
The alias is only importing http and you can avoid using it if you want. The rest are partitioned into their protocols and go mod will trim off the unused deps. 

What are you seeing? Maybe you have an wanted import?

**Comment by tamalsaha** [comment]
But I think Go does pruning post dependency resolution. Creating separate modules will skip unused protocols from the dependency resolution.

**Comment by n3wscott** [comment]
Ok, go mod did not do what I was expecting at all. The new modules under `v2/protocol` work and everything is fine here in the repo, but when you attempt to import these, one release does not release the submodules.

Here is RC5 : https://github.com/cloudevents/sdk-go/releases/tag/v2.0.0-RC5

it lacks the protocols now, as expected, but the sub-modules also need a new tag:

https://github.com/cloudevents/sdk-go/releases/tag/v2%2Fprotocol%2Fstan%2Fv1.0.0-RC5

https://github.com/cloudevents/sdk-go/releases/tag/v2%2Fprotocol%2Fkafka_sarama%2Fv1.0.0-RC5

Note the `v1.0.0-RC5` tag. Which now is a bigger sync problem around which version is which and which go with what....

To get the protocols back to v2, they need to 1- add a new v2 dir like `v2/protocol/stan/v2`, or 2- move the protocol dirs to the top level, and still do all the `v2` dir workarounds. Moving the folders would shorten the release tags.

The advice from the gophers is to make separate repos for each protocol.

In terms of code, we have some choices:

- Protocols can continue to have `.../sdk-go/v2/...` in their path, and we can bump them to v2 as well but the full import results in `github.com/cloudevents/sdk-go/v2/protocols/stan/v2` which is goofy. And this is api breaking for everyone using anything but http.

- we can revert the adding of go mod files and be ok with the dep resolution.

**Comment by n3wscott** [comment]
We might be able to just revert the sub-module changes and wait for go 1.16 per https://github.com/golang/go/issues/36460 which should fix the original issue of dep resolution speed.

**Comment by slinkydeveloper** [comment]
> The advice from the gophers is to make separate repos for each protocol.

But then we have an explosion of repos... But most important, I think we should keep this project a monorepo, given the rate of changes we had and we will continue to have in the internals of protocol implementations

**Comment by slinkydeveloper** [comment]
Solved with 2.0.0 release
