### ISSUE TITLE
Accept transformers is Send/Request method signatures

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#451]
Because transformers are usually per-request, it doesn't make sense to assign them to a Send/Request implementation like here: https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/http/protocol.go#L27

**Comment by n3wscott** [comment]
I can buy this argument. var-arg transformers that run after the already set protocol ones.

**Comment by slinkydeveloper** [comment]
I think we should remove the ones set in the protocol, since imo they are not really useful.
