### ISSUE TITLE
Close lifecycle with Client and Protocol 

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#452]
At the moment we don't have a specified way to close a connection, nor it's clear who should close the receiver opened by `Client.StartReceiver`.

We need to define:

1. Closing the `ctx` of `StartReceiver` closes only the receiver, or the whole protocol?
2. Should we have a `Close` method on the Client? Or should the user invoke `Protocol.Close()` to close the connection?
3. What happens if a user invokes `Protocol.Close()` while a Receiver is started?

As soon as we reach an agreement, we need a test to check this behaviour in various protocols and document it.

**Comment by slinkydeveloper** [comment]
My proposal is:

1. closing the `ctx` closes only the receiver. E.g. for Kafka this means that the `ConsumerGroup` is closed, but not the connection to kafka (`sarama.Client`)
2. No, we should tell users to invoke `protocol.Close()` to close the connection
3. `Protocol.Close()` should stop the receiver too

**Comment by dan-j** [comment]
Can I add suggestions/amendments to your answers 2) and 3):

2) `protocol.Close()` should only close the actual connection if the protocol created the connection. Some (maybe all) of the protocols allow users to pass in their own connection using an alternative constructor. 
3) Should `protocol.Close()` unblock the call to `client.StartReceiver()`? This would mean somehow propagating a message from the protocol into the `StartReceiver()` method.

**Comment by slinkydeveloper** [comment]
> protocol.Close() should only close the actual connection if the protocol created the connection. Some (maybe all) of the protocols allow users to pass in their own connection using an alternative constructor.

Agree

> Should protocol.Close() unblock the call to client.StartReceiver()? 

Yes, i think it's the behaviour you would expect.

**Comment by n3wscott** [comment]
> My proposal is:
> 
> 1. closing the `ctx` closes only the receiver. E.g. for Kafka this means that the `ConsumerGroup` is closed, but not the connection to kafka (`sarama.Client`)

You can't always assume this is not the context for the entire process. The reason the cloudevents client uses context all over the place is to do exactly this: close the thing down.

> 2. No, we should tell users to invoke `protocol.Close()` to close the connection

Or we get rid of `.Close()` and the caller can choose to pass a unique context to both client and the protocol. Continuing to use context `cancel()` to end the components.

> 3. `Protocol.Close()` should stop the receiver too

We can have a channel that sends errors and state back up, sure. It does not make a whole lot of sense for the client to continue, although there are components like nats that reconnect so if we made a contract that the protocol can implement, then they can choose when the disconnection is terminal.

**Comment by n3wscott** [comment]
To make it more clear: cancel on context for client stops the client. We can make it so the client does not do anything to the protocol. The protocol stops when the context is canceled. If you want them to stop at the same time, you can use the same context. If you want to control them independently, make two contexts with cancel functions (or timeouts or whatever).

This way, if the parent context is canceled (like the process gets a sig-term) then both components still try to shut down in the expected way.

**Comment by slinkydeveloper** [comment]
I like the thing of using the `Context` always. So your proposal is:

* Drop `Close()` (otherwise we would have two endpoints for closing things)
* Have the constructed `ctx` as the signal to close the protocol

**Comment by slinkydeveloper** [comment]
Ok I started digging into this and I think it's not a good idea to use context to close the whole protocol, but keeping `Close()` imo it's a good idea. My points are:

* Most `Sender`, `Receiver` or `Protocol` we have should start a goroutine to poll the context.
* Looking around to other golang APIs, `Close()` makes obvious that you can, or better you must, close the sender/receiver/protocol (like a persistent connection to Kafka) when you don't need it anymore, while `ctx` is mostly used for "transient" operation abortion (like cancel producing a message, stop a receiver and so on), which is the usage that client does of it.
* Implementation is generally easier having `Close()` and `ctx`. For example: you say that the user could potentially assign the same context both to protocol and to start receiver. In case of Kafka, this could end up in a race condition where I close the kafka client, but the consumer group is still not closed. That means that we need another context, or some internal lock to coordinate the close operation.
