### ISSUE TITLE
Implement parallelism in client for Receive/Responder

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#453]
Now in `Client` there is a single poll loop for `Receive`/`Responder` https://github.com/cloudevents/sdk-go/blob/master/v2/client/client.go#L205

We should probably have N goroutines polling, where N presumably could be `GOMAXPROCS` (one poll loop per OS thread).

This also means that the protocols implementations should have a sized channel, presumably same of number of Goroutines: https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/http/protocol.go#L57

**Comment by n3wscott** [comment]
Yes we can do this. I don't think it removes or changes the API. Let's do this after v2.0.0 cuts.

**Comment by slinkydeveloper** [comment]
It needs a new API to set the parallelism, but yeah we can do that after v2
