### ISSUE TITLE
Possible to set a default version if ce-specversion is not in the request header

### ISSUE THREAD

**Issue by mattcui** [cloudevents/sdk-go#465]
I have a requirement to get notified when the certificate is renewed by certmgr, certmgr provides a feature to allow to register a callback url where the notification could be sent to when the certificate is renewed as the curl command does below:

```
curl -X 'POST' '<callback url>' -H 'connection: close' -H 'content-type: application/json' -H 'accept: application/json' -H 'host: 127.0.0.1' -d $'{"data":"xxxxxx"}'
```

I wrote a goland app based on https://knative.dev/docs/eventing/samples/helloworld/helloworld-go/ to receive the notification.  There returned the error like below when sending the POST request as above:

{"level":"error","ts":1587287459.1181471,"logger":"fallback","caller":"http/transport.go:616","msg":"failed to get non-nil event from MessageToEvent","stacktrace":"github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/Users/mattcui/myspace/cert-renewal-service/src/github.ibm.com/cuixuex/cert-renewal-service/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:616\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/Users/mattcui/myspace/cert-renewal-service/src/github.ibm.com/cuixuex/cert-renewal-service/vendor/go.opencensus.io/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}

I could get the expected result if I add `Ce-specversion: 0.3` in the Header, from the code, I saw there will report `cloudevents version unknown` error if there doesn't specify `Ce-specversion` in the request header -> https://github.com/cloudevents/sdk-go/blob/master/v1/cloudevents/transport/http/transport.go#L259-L269 , I am wondering if there could set a default `Ce-specversion` version if such header if not specified in the request so that the cloudevent could support some products which doesn't use cloudevent yet. Thanks.

/cc @duglin

**Comment by slinkydeveloper** [comment]
Hi @mattcui, the `Ce-specversion` header is a mandatory field of cloudevent (https://github.com/cloudevents/spec/blob/v1.0/spec.md#specversion) and the sdk uses it to distinguish a non cloudevent request to a cloudevent request (Also a note here https://github.com/cloudevents/spec/blob/master/http-protocol-binding.md#3-http-message-mapping)

There is any specific reason why you cannot add the header?

**Comment by mattcui** [comment]
@slinkydeveloper thanks for you reply, as I tried to get notified from an external service which is not under my control, it doesn't allow to bing any custom headers/ I tried to append header in `virtual service` or `ingresses.networking.internal.knative.dev`, but the change is reverted by reconciliation immediately.  Do you know if there is a way in Knative to append the headers and forward the request to a specific knative service? Thanks.

**Comment by slinkydeveloper** [comment]
TBH I don't know, I think you should bring this question on the slack channel of knative

**Comment by slinkydeveloper** [comment]
I close as it's irrelevant for this project, reopen if you need it

**Comment by duglin** [comment]
I can see something in Knative helping here... some sort of "CE creator" proxy thing.

However, this is kind of related to a question that came up in the CE WG chats... what should an SDK do when it gets an event that isn't a CE?  I suspect most will generate an error and that's a valid choice. However, it might not be unreasonable for the user to be able to specify that it should be converted into a CE per some user-defined rules.  E.g.
- ce-source = HTTP "User-agent" value, else "unknown"
- ce-id = new UUID
- ce-type = HTTP Content-Type value, else "unknown"
- ce-specversion  = 1.0

Just a thought...

**Comment by slinkydeveloper** [comment]
Look at that: https://github.com/cloudevents/sdk-go/issues/483#issuecomment-621301002
