### ISSUE TITLE
Receiving Structured Events

### ISSUE THREAD

**Issue by jonatasbaldin** [cloudevents/sdk-go#468]
Hi there 👋

I'm trying to receive a Structured Event from Azure, but when I try to print the Event, I got a validation failed, but the fields seem to be correct.

Here's the code to receive:
```golang
func display(event cloudevents.Event) {
	log.Print(event.String())
}

func main() {
        // Tried both transports
	// transport, err := cloudevents.NewHTTPTransport(cloudevents.WithStructuredEncoding())

	transport, err := cloudevents.NewHTTPTransport(cloudevents.WithEncoding(cloudevents.HTTPStructuredV1))
	if err != nil {
		log.Fatalf("failed to construct transport, %v", err)
	}

	client, err := cloudevents.NewClient(
		transport,
	)
	if err != nil {
		log.Fatalf("failed to construct client, %v", err)
	}

	ctx := context.Background()

	err = client.StartReceiver(ctx, display)
	if err != nil {
		log.Fatalf("failed to start receiver, %v", err)
	}

	log.Printf("listening on port %d\n", 8080)
}
```

This is the data being received:
```
POST / HTTP/1.1
Content-Type: application/cloudevents+json; charset=utf-8
origin: eventgrid.azure.net
aeg-subscription-name: KONNEK
aeg-delivery-count: 0
aeg-data-version: 1
aeg-metadata-version: 0
aeg-event-type: SubscriptionDeletion
Host: 59af7c95.ngrok.io
Content-Length: 601
X-Forwarded-Proto: https
X-Forwarded-For: 51.137.16.225

{
  "id": "7560d26b-c023-47d4-8e50-9461f5e42f8f",
  "source": "/subscriptions/xxx/resourceGroups/konnek/providers/Microsoft.Storage/storageAccounts/konnek",
  "specversion": "1.0",
  "type": "Microsoft.EventGrid.SubscriptionDeletedEvent",
  "dataschema": "#1",
  "subject": "",
  "time": "2020-04-22T19:35:32.522804+00:00",
  "data": "{\r\n  \"eventSubscriptionId\": \"/subscriptions/xxx/resourceGroups/konnek/providers/Microsoft.Storage/storageAccounts/konnek/providers/Microsoft.EventGrid/eventSubscriptions/konnek\"\r\n}"
}
```

And this is the validation error that I get when doing `log.Print(event.String())`:
```
2020/04/22 22:22:21 Validation: invalid
Validation Error: 
id: MUST be a non-empty string
source: REQUIRED
type: MUST be a non-empty string
Context Attributes,
  specversion: 1.0
  type: 
  source: 
  id: 
  datacontenttype: application/cloudevents+json; charset=utf-8
Data,
  {...}
```

I was expecting that using the Structured transport the JSON body would be correctly converted into the Event struct, but it's failing somewhere 🤔

Any ideas?

Thanks!

**Comment by deissnerk** [comment]
Well, the error message is strange. The original event has an empty subject, which is not compliant to the spec. `subject` is OPTIONAL, but MUST be a non-empty string if present. So that could be a problem.

**Comment by jonatasbaldin** [comment]
Hey @deissnerk, thanks for the reply. I tried an event with a non-empty subject and the error remains the same. 

I tried to make the Event with only the REQUIRED parameters, but it also failed with the same error.

```
{
    "id": "23ef07ec-201e-001b-4432-1900ce06145c",
    "source": "/subscriptions/xxx/resourceGroups/konnek/providers/Microsoft.Storage/storageAccounts/konnek",
    "specversion": "1.0",
    "type": "Microsoft.Storage.BlobCreated",
    "data": {
        "api": "PutBlob",
        "clientRequestId": "xxx",
        "requestId": "23ef07ec-201e-001b-4432-1900ce000000",
        "eTag": "0x8D7E749F70756A5",
        "contentType": "image/png",
        "contentLength": 12068,
        "blobType": "BlockBlob",
        "url": "https://konnek.blob.core.windows.net/konnek/1F32C_color.png",
        "sequencer": "000000000000000000000000000021020000000004d510f0",
        "storageDiagnostics": {
            "batchId": "52b3a05d-a006-0105-0032-199c76000000"
        }
    }
}
```

**Comment by slinkydeveloper** [comment]
@jonatasbaldin are you using the sdk v2? to me looks like the content type is not recognized, and it should be already fixed by https://github.com/cloudevents/sdk-go/pull/467

**Comment by jonatasbaldin** [comment]
I'm using v1 (but without any reason). Should I just go v2?

**Comment by slinkydeveloper** [comment]
Try the v2 please (master atm, because the #467 is still unreleased) and check if you still have the problem

**Comment by jonatasbaldin** [comment]
Will do :) v2 is not stable yet, right? Is there anything I should be aware of?

**Comment by slinkydeveloper** [comment]
We started stabilizing it, it's not far to being GA :smile: Quite a lot of things changed, check out the readme and this doc https://github.com/cloudevents/sdk-go/tree/master/docs

**Comment by jonatasbaldin** [comment]
Cool, thanks for all the links :D I'll try the v2 this weekend and let u know :)

**Comment by jonatasbaldin** [comment]
hey hey hey, it does work in `v2`, using the context as `ctx = cloudevents.WithEncodingStructured(ctx)` 🎉

gonna close this for now :)
