### ISSUE TITLE
Should the SDK respond with "415: Unsupported Media Type" when the Content-Type is unsupported?

### ISSUE THREAD

**Issue by antoineco** [cloudevents/sdk-go#483]
I made the point in #482 that data sent over the HTTP protocol without a valid `Content-Type` header was acknowledged by a `200: OK` code although the request is in fact dropped by the SDK.

I believe this is wrong and conflicts with RFC 2616. I would suggest the SDK responds with
* 415: Unsupported Media Type, when the Content-Type header is not supported
* 400: Bad Request, when the data couldn't be recognized as a CloudEvent payload

@slinkydeveloper suggested in https://github.com/cloudevents/sdk-go/pull/482#issuecomment-621148893 that I open an issue to discuss this:

> That's a really interesting point here, i never thought about that... I feel this kind of problem should be brought at spec level, because it gives an hint on how to parse the event https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#3-http-message-mapping but it also states _Otherwise it defaults to binary mode._ which is clearly what we don't do in the sdk, because in the end the user needs a distinction between event/non event. So the criteria on replying with a content type not supported is interesting, i think you should open an issue on the spec about that

**Comment by slinkydeveloper** [comment]
@n3wscott any opinions on this one?

**Comment by n3wscott** [comment]
I agree. A 4xx level error in response seems like the right thing.

415 seems to fit. returning 200 sounds like it was just bypassing all our code and returning and that is the default that the writers use. I think this is an easy fix.

**Comment by slinkydeveloper** [comment]
My proposal to handle this issue is:

* if the receiver function expects an event, then **the client** fails if encoding is unknown and protocol correctly writes the error with the right status code (checking if error wraps binding.ErrEncodingUnknown should suffice)
* if the receiver function doesn't expect an event, message is just dropped
* if the user really wants to do crazy stuff like converting non events to event, then he should use the protocol directly

**Comment by n3wscott** [comment]
I like the idea of giving the client a chance to fix (or report) an event that was invalid rather than do it at the protocol level. This gives us hooks to change the response code or behavior by replacing the client without changing the protocol impl. That seems nice.

**Comment by duglin** [comment]
> if the user really wants to do crazy stuff like converting non events to event, then he should use the protocol directly

can you elaborate on what you mean by "use the protocol directly" ?  You mean not use the SDK?

**Comment by slinkydeveloper** [comment]
I mean use the `http.Protocol`, aka the protocol level as described here: https://cloudevents.github.io/sdk-go/concepts.html#investment-level

**Comment by slinkydeveloper** [comment]
We can create an example specific for that

**Comment by antoineco** [comment]
TIL. Thanks for the link @slinkydeveloper.

**Comment by slinkydeveloper** [comment]
I'm working on the example

**Comment by slinkydeveloper** [comment]
Here it is: https://github.com/cloudevents/sdk-go/pull/496

**Comment by antoineco** [comment]
@slinkydeveloper the example is nice 👍  However, how does it relate to expecting a meaningful _HTTP_ response from the SDK's receiver?

This here is a common use case for starting a receiver:
```console
func main() {
    cli, _ := cloudevents.NewDefaultClient()
    cli.StartReceiver(ctx, func(cloudevents.Event) {})
}
```
Yet, sending this payload still returns `200 OK` instead of `400 Bad Request`:
``` console
$ curl -D- -H "Content-Type: application/cloudevents+json" localhost:8080/ -d'{"foo": "bar"}'
```
We should have better defaults.

**Comment by slinkydeveloper** [comment]
I'll work on that too :wink:

**Comment by slinkydeveloper** [comment]
I drafted the expected behaviour in these tests: https://github.com/cloudevents/sdk-go/pull/498/files#diff-3666ce1687203ab4a81aec71bee67724R17

**Comment by mattcui** [comment]
@slinkydeveloper  I wanna create an app to receive some notifications from an external service, it's not an cloud event (no ce specific hearders), just  `application/json` type,  Is there an example to start a listener server and get POST request data through sdk v2? Thanks.

/cc @antoineco
