### ISSUE TITLE
Client.StartReceiver causes panic if Kafka connection is lost

### ISSUE THREAD

**Issue by timjonesdev** [cloudevents/sdk-go#487]
https://github.com/cloudevents/sdk-go/blob/v2.0.0-RC2/v2/client/client.go#L192-L200

```golang
// Start the opener, if set.
if c.opener != nil {
	go func() {
		// TODO: handle error correctly here.
		if err := c.opener.OpenInbound(ctx); err != nil {
			panic(err)
		}
	}()
}
```

I'm just getting started trying to use the SDK with Kafka, and I'm trying to test how to recover from a lost connection. It seems that this panic causes my application to crash, and I'm wondering if there are plans to address the `TODO`.

If not, can you help with ideas for how to recover from the panic? Thank you for your time!

**Comment by slinkydeveloper** [comment]
Hi @timjonesdev, thanks for spotting the issue! There is an hidden gem in the library we use for kafka i need to fix, I'll assign this issue to myself and i'll ping you when it's ready.

**Comment by slinkydeveloper** [comment]
Check out the https://github.com/cloudevents/sdk-go/issues/488

**Comment by timjonesdev** [comment]
Awesome! Thanks for the quick response!

**Comment by timjonesdev** [comment]
I wanted to mention, this fixed my issue. I am now able to reconnect to Kafka once I restart it. Thanks again!
