### ISSUE TITLE
Why even attempt to convert resp to event when protocol.Request returns error?

### ISSUE THREAD

**Issue by yolocs** [cloudevents/sdk-go#512]
Here:

https://github.com/cloudevents/sdk-go/blob/97abfeb3da0bed09e395bff2c5bcf35b6435cb5f/v2/client/client.go#L142-L166

When `requester.Request` returns an error (line 144), it still attempts to convert the resp to an event (line 154). The error message seems confusing in certain cases. Here is an example.

Call `client.Request` to an HTTP server that always returns 400. The error message I see is:

```
time="2020-05-19T20:53:57Z" level=error msg="Failed to seed event (id=eed6e5df-917e-42cf-9e30-40120f003895) to target \"http://actor.m0.svc.cluster.local\": 400: %!w(*protocol.Receipt=&{false  []}); failed to convert response into event: unknown Message encoding"
```

This is confusing because I'm replying 400 to indicate an error, in which case the sdk shouldn't even attempt to convert my resp.

**Comment by slinkydeveloper** [comment]
I think you're right, it's probably missing an `if !protocol.IsACK(err)` statement
