### ISSUE TITLE
http: Write the message from http.Result in the body

### ISSUE THREAD

**Issue by antoineco** [cloudevents/sdk-go#514]
A [`http.Result`](https://github.com/cloudevents/sdk-go/blob/97abfeb/v2/protocol/http/result.go#L20-L25) is composed of both a status and a message. Yet, only the status is written in the response writer:

https://github.com/cloudevents/sdk-go/blob/97abfeb/v2/protocol/http/protocol.go#L316-L319

I suggest we also write the message with a `text/plain` content type.

**Comment by slinkydeveloper** [comment]
> I suggest we also write the message with a text/plain content type

Only when the status is a failing status (between 200 and 299 included)

**Comment by n3wscott** [comment]
I am not sure about this. The result will not be a cloudevent. If the function or whatever it is does throw an error and returns the error as text/plain, I am going to bet it will blow up the parser on the caller side.

**Comment by antoineco** [comment]
A CloudEvent would also be fine, any kind of feedback would be as long as we don't lose the error message. The question is, what type do we set on the event?

**Comment by n3wscott** [comment]
> A CloudEvent would also be fine, any kind of feedback would be as long as we don't lose the error message. The question is, what type do we set on the event?

I think you would get some cycles in a model like Knative Brokers where the trigger cycles the response back to the broker.

My thinking is that the error is not for the caller, it is for the implementor. 

perhaps we could return a json object and have it not be json but this is introducing a lot of logic into the sdk that is not in the spec.

You are free to return an error from your code in the form of a cloudevent and it does not have to be a sdk feature. a 4xx level response + a cloudevent is valid.

**Comment by antoineco** [comment]
> it does not have to be a sdk feature

Should we perhaps remove that message field from the `HTTPResult` then if the SDK is not supposed to use it? I find it a bit confusing that a handler can have a `HTTPResult` as return value but only return the status from it. Maybe it just don't understand the intended workflow.

**Comment by slinkydeveloper** [comment]
> I am going to bet it will blow up the parser on the caller side.

Perhaps the caller will skip the parsing, because the error is > 299?

**Comment by slinkydeveloper** [comment]
> Should we perhaps remove that message field from the HTTPResult then if the SDK is not supposed to use it? 

The sdk potentially use it for logging IIRC

**Comment by antoineco** [comment]
> You are free to return an error from your code in the form of a cloudevent and it does not have to be a sdk feature. a 4xx level response + a cloudevent is valid. (https://github.com/cloudevents/sdk-go/issues/514#issuecomment-632829270)

You're right, the `func(/*...*/) (*event.Event, protocol.Result)` signature is probably more suitable than `func(/*...*/) protocol.Result` for my use case. I'll switch to that.

Thanks for the feedback folks.
