### ISSUE TITLE
Simpler result checking than !cloudevents.IsACK()

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/sdk-go#526]
Now to check if a Send/Receive was completed succesfully (without caring about the error side), the user should do:

```go
if !cloudevents.IsACK(result) {
  // Something happened but i don't care what, i just log the error
  log.Printf("Something wrong: %s", result.Error())
} else {
    // It worked
}
```

The condition is not trivial to understand for somebody that doesn't have knowledge of the sdk, and in particular of the result type. I propose to create a simpler method that has the same semantic of `!cloudevents.IsACK` but it's simpler to use to cover such use cases.

**Comment by slinkydeveloper** [comment]
An idea:

* `IsSuccess()` == `cloudevents.IsACK()`
* `IsFailure()` == `!cloudevents.IsACK()`

**Comment by slinkydeveloper** [comment]
cc @n3wscott

**Comment by n3wscott** [comment]
what about the case where the result is an ACK and also an error?

**Comment by slinkydeveloper** [comment]
I suppose `IsSuccess()` should identify it as well? Can you do an example?

**Comment by dan-j** [comment]
I agree that it's not trivial to understand how the `protocol.IsACK()` or `procotol.IsNACK()` works, after just spending over an hour studying the in's and out's of it, however I can't see how your `IsSuccess()`/`IsFailure()` idea would improve it?

Why not just keep `protocol.IsACK()` and remove `protocol.IsNACK()`? 

To help argue the point, I see four possible permutations of `error` which you can pass to either function (forgive me if my logic is wrong, in which case this whole argument falls down, although it implies these edge cases needs tests)

- if `err == nil` then `IsACK(err) == true` and `IsNACK(err) == false`
- if `err` wraps a `protocol.Receipt(true)` then `IsACK(err) == true` and `IsNACK(err) == false`
- if `err` wraps a `protocol.Receipt(false)` then `IsACK(err) == false` and `IsNACK(err) == true`

All the above 3 permutations can produce the same result by just doing `!protocol.IsACK(err)`. I can only see a logical difference between then when it comes to this fourth permutation:

- if `err != nil` and doesn't wrap a receipt, then `IsACK(err) == false` and `IsNACK(err) == false` (unless the underlying `error` also implements `Is()` and returns `true`).

Is there any reason why you'd want this fourth functionality? It seems overly convoluted and one which the majority of people will never require. The API could just be set that `err == nil` means ACK and `err != nil` means NACK and force consumers to abide by it.

If you really wanted the edge case where an error should also ACK, then you could export a `var ErrWithACK` which behaves identically to `protocol.Receipt(true)`

Thoughts?

**Comment by slinkydeveloper** [comment]
> Why not just keep protocol.IsACK() and remove protocol.IsNACK()?

I'm not proposing to remove IsACK and IsNACK, I'm proposing to have a method that avoids a user to do `!cloudevents.IsACK()` to catch a failure of whatever type, that's why `IsSuccess()` and `IsFailure()`, so I can translate this code:

```golang
res := c.Send(ctx, e)
if !cloudevents.IsACK(res) {
	log.Printf("Failed to send: %v", res)
} else {
	var httpResult *cehttp.Result
	cloudevents.ResultAs(res, &httpResult)
	log.Printf("Sent %d with status code %d", i, httpResult.StatusCode)
}
```

To:

```golang
res := c.Send(ctx, e)
if cloudevents.IsFailure(res) {
	log.Printf("Failed to send: %v", res)
} else {
	var httpResult *cehttp.Result
	cloudevents.ResultAs(res, &httpResult)
	log.Printf("Sent %d with status code %d", i, httpResult.StatusCode)
}
```

> If you really wanted the edge case where an error should also ACK

The point is that we need it. As you see in the example above, in http protocol we wrap in the result ACK some informations like status code. Other protocols could do the same wrapping in the acks some informations about the sent message (eg the level of ack). That's the whole point why we made this `protocol.Result` type.

**Comment by dan-j** [comment]
Makes sense about the HTTP protocol, I've never looked into that specific one.

Not really sure what my opinion is in that case, the thing that confused me the most was in my adapter code between the SDK to my `Service` components, what the default receipt should be in event of an error without receipt. 

I've ended up saying that all errors returned from my Service should ACK, unless it's a `Receipt(false)`, which has resulted in my code doing this:

```
response, err := handleEventData(ctx, data)
if err != nil && !protocol.IsNACK(err) {
  err = nil
}

return response, err
```

I don't really like it, but can't see an alternative in the current SDK (it also highlights a use of my 4th permutation which I initially thought no-one would need, so I kind of retract my initial comment 😅).

But back on topic, I don't see how adding a `IsFailure()` function simplifies it, you still need to understand how errors are handled internally to actually know what "failure" means.

How about another utility function (feel free to choose a different name) which adds a receipt to the error based on what the user wants the default as, providing there isn't already receipt attached:

```
func ReceiptDefault(err error, defaultACK bool) error {
  if !protocol.IsACK(err) && !
}
```

Then I can change my adapter code to:

```
response, err := handleEventData(ctx, data)
return response, protocol.ReceiptDefault(err, true)
```

**Comment by dan-j** [comment]
Additionally, `ReceiptDefault(...)` should return `nil` if `err == nil`

**Comment by n3wscott** [comment]
```
func ReceiptDefault(err error, defaultACK bool) error {
  if protocol.IsACK(err) || protocol.IsNACK(err) {
    return err
  }
  
  return &Receipt{ Err: err, ACK: defaultACK }
}
```

This code is not true is the issue, we are really talking about three distinct things:

1. I sent and the target accepted. ACK aka IsACK
2. I sent and the target did not accept: NACK aka IsNACK
3. I failed to send and the target is unaware: error aka !IsACK && !IsNACK


Perhaps the API would have been simpler if we returned `(Receipt, error)` and broken out the 3. case into a distinct thing, and then Receipt could be nil in that case.

I think this logic is what Slinky is proposing with `IsFailure`, it turns `!IsACK && !IsNACK` into `IsFailure`.

I wonder if we could use that same logic but a different name like `Undelivered` to mean the event never left the local system.

Then we can write:

```go
var httpResult *cehttp.Result
if result := c.Send(ctx, e); result.Undelivered() {
	log.Printf("Failed to send: %v", res)
} else if cloudevents.ResultAs(result, &httpResult) {
	log.Printf("Sent %d with status code %d", i, httpResult.StatusCode)
} else {
	// you get here if this is not using http protocol.  
}
```

**Comment by deissnerk** [comment]
> Perhaps the API would have been simpler if we returned (Receipt, error) and broken out the 3. case into a distinct thing, and then Receipt could be nil in that case.
+1
I would even argue that Result, Receipt and error are distinct things.

**Comment by slinkydeveloper** [comment]
Yes @n3wscott  `Undelivered` is exactly what i was searching for: a good part of user base just checks if the event was undelivered, outputting the error no matter which one (500 from the server or i/o timeout).

`Undelivered()` == `!cloudevents.IsACK()` right?

**Comment by n3wscott** [comment]
> Undelivered() == !cloudevents.IsACK() right?

`Undelivered` == `!cloudevents.IsACK() && !cloudevents.IsNACK()` 

It is a pure error on your side. The event never left.

**Comment by n3wscott** [comment]
> +1
> I would even argue that Result, Receipt and error are distinct things.

This will have to be tracked for SDK v3 @deissnerk as it is an API breaking change.

**Comment by slinkydeveloper** [comment]
@n3wscott that's not what i meant with this issue: I'm fine with `Undelivered`, but what i was asking for it an helper that just returns true when the result is a failure or because it was not delivered or because of a nack, just something nicer than `!cloudevents.IsACK`. That's why this comment: https://github.com/cloudevents/sdk-go/issues/526#issuecomment-636813024
