### ISSUE TITLE
Whether the extension attribute can not contain "-" ?

### ISSUE THREAD

**Issue by yuchunyu97** [cloudevents/sdk-go#533]
I get a CloudEvents via HTTP, some headers are like this:

```
Ce-Fc-Code-Checksum: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
I try to use go sdk to parse this event, like this:

```
...
evt, result := c.Request(ctx, event)
...
evt.DataAs(MyStruct)
...
```

but, the `evt` is `nil`. I found the following code in the source code:

https://github.com/cloudevents/sdk-go/blob/4ca23c8455477e8d1fbb76ee928909bf818ebdb4/v2/event/eventcontext_v1.go#L72-L78

https://github.com/cloudevents/sdk-go/blob/4ca23c8455477e8d1fbb76ee928909bf818ebdb4/v2/event/extensions.go#L24

It seems because of my extension attribute key `Ce-Fc-Code-Checksum` have `-`, but I can't find the description of the extension attribute key name in the specification:

https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#313-metadata-headers

Can someone help me?

**Comment by slinkydeveloper** [comment]
Hi, it's explained here:

* https://github.com/cloudevents/spec/blob/v1.0/spec.md#extension-context-attributes
* https://github.com/cloudevents/spec/blob/v1.0/spec.md#attribute-naming-convention

> CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.

So it seems like the sender is sending an invalid Cloudevent and the sdk is correctly validating it
