### ISSUE TITLE
Which versions of Go are supported?

### ISSUE THREAD

**Issue by grant** [cloudevents/sdk-go#536]
Which versions of Go are supported in this SDK?

I can't find it listed in the README.

```
/go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0/types/value.go:306:27: reflect.ValueOf(v).IsZero undefined (type reflect.Value has no field or method IsZero)
note: module requires Go 1.13
```

**Comment by n3wscott** [comment]
https://github.com/cloudevents/sdk-go/blob/master/v2/go.mod#L28

**Comment by grant** [comment]
Can we document this? I was running tests with Go 1.12, 1.13, 1.14 and had issues.

**Comment by n3wscott** [comment]
Added to the readme at the top level. Let me know if this is enough or if there is some kind of standard way?
