### ISSUE TITLE
"http: superfluous response.WriteHeader call" error, unreceived events when serving via http.ListenAndServe 

### ISSUE THREAD

**Issue by maschmid** [cloudevents/sdk-go#537]
Basing the receiver code on https://github.com/cloudevents/sdk-go/blob/master/samples/http/receiver-gorilla/main.go  , the receiver sometimes doesn't receive events, when events are sent in parallel, showing the following errors in logs:

```
http: superfluous response.WriteHeader call from github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).ServeHTTP.func2 (protocol.go:321)
```

The same code based on https://github.com/cloudevents/sdk-go/blob/master/samples/http/receiver/main.go works fine.

See https://github.com/maschmid/cloudevents-superfluous-error for a reproducer, containg both a working and broken variants.

**Comment by n3wscott** [comment]
Thanks for the example repo, this helps a lot...

ok findings so far, it looks like this happens when the receiver returns a 500, still digging in.

```going to write out status, 500
2020/06/25 09:07:33 http: superfluous response.WriteHeader call from github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).ServeHTTP.func2 (protocol.go:323)```

**Comment by n3wscott** [comment]
The error seems to be related to the size of the payload.

```
going to write out status, 500, failed to convert Message to Event: http: invalid Read on closed Body
```

**Comment by n3wscott** [comment]
Perhaps this: https://github.com/golang/go/issues/4637#issuecomment-66073563

We might be doing something wrong... 😬

**Comment by n3wscott** [comment]
got it.

from net/http server.go:93

```
// A ResponseWriter may not be used after the Handler.ServeHTTP method
// has returned.
```

PR pending to fix.
