### ISSUE TITLE
Old Sarama Dependency

### ISSUE THREAD

**Issue by mantzas** [cloudevents/sdk-go#546]
Hi, 

I was wondering if there is any reason for sarama to be in version 1.19.0 (2018-09-27)?

**Comment by slinkydeveloper** [comment]
Not really, I'm gonna dump to latest version

**Comment by mantzas** [comment]
Maybe not exactly the latest, but the one before that. 1.26 seemed to have some troubles.
I could also do this for you if you like!

**Comment by slinkydeveloper** [comment]
I'll be happy to see your contribution :smile:
