### ISSUE TITLE
Parsing CloudEvent from HTTP response for 4xx,5xx status codes.

### ISSUE THREAD

**Issue by matejvasek** [cloudevents/sdk-go#558]
Spec states `Events can be also be transferred in HTTP responses and with all HTTP status codes that permit payload body transfers.` However when I do request that results in 500:
```go
receivedEvt, resp := cloudEventClient.Request(context.Background(), *evtToSend)
```
only error is set (correctly to "500:"), the `receivedEvt` is nil, despite the fact that response contained body with CloudEvent.

**Comment by matejvasek** [comment]
@n3wscott wdyt?

**Comment by n3wscott** [comment]
This should work if the headers are correct as well, can you make a little demo or paste the raw http body of the response?

**Comment by matejvasek** [comment]
Response as seen in WireShark:
```
HTTP/1.1 500 Internal Server Error
Date: Mon, 27 Jul 2020 10:43:55 GMT
Content-Type: application/cloudevents+json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{
  "specversion": "1.0",
  "type": "core.errorresponse",
  "source": "/of",
  "id": "de66d47f-6521-4b86-bc04-0b421e41367b",
  "time": "2020-07-27T10:43:55.9400808Z",
  "data": "{\"ErrorCode\":null,\"ErrorDetails\":\"Internal runtime failure. Please refer to runtime logs for details\"}",
  "datacontenttype": "application/json"
}
```

**Comment by matejvasek** [comment]
@n3wscott I think that this may be deliberate:
somewhere in the code:

```go
	var result protocol.Result
	if resp.StatusCode/100 == 2 {
		result = protocol.ResultACK
	} else {
		result = protocol.ResultNACK
	}
```
then later

``` go
	if !protocol.IsACK(err) {
		return nil, err
	}
```

but doesn't that go against spec `Events can be also be transferred in HTTP responses and with all HTTP status codes that permit payload body transfers.` ?

**Comment by n3wscott** [comment]
in the case of the above event and the caller code of:

```
receivedEvt, resp := cloudEventClient.Request(context.Background(), *evtToSend)
```

I would expect `resp` to be a NACK, but also `receivedEvt` to be the full event in response. Let me poke around...

**Comment by n3wscott** [comment]
YES, it is a simple fix.. 😅 one sec

**Comment by n3wscott** [comment]
Thanks for the bug @matejvasek !! The simple fix is this: https://github.com/cloudevents/sdk-go/pull/559/files#diff-4fd5b8ce98982998f08e4be1a9c74c50R152

Give it a try locally and see if it solves your issue.

**Comment by matejvasek** [comment]
Sorry for late reply. Thanks @n3wscott , it works!
