### ISSUE TITLE
Enable Trace Context Propagation in the Default HTTP Client

### ISSUE THREAD

**Issue by ian-mi** [cloudevents/sdk-go#572]
For v2 it was decided that trace context propagation should be opt-in rather than opt-out. Over HTTP, however, there should be little downside to enabling trace context propagation using the W3C tracecontext headers as this does not require modifying event extensions. Therefore I propose that tracing middleware to the HTTP protocol used by NewDefaultClient.

**Comment by n3wscott** [comment]
There is a client that should be created that adds the tracing https://github.com/cloudevents/sdk-go/blob/589ccf58301886a6aa2165ba77f16f4c02cf4260/v2/client/client_observed.go#L14

All observability should be pushed there. The longer term goal is to break the observed parts into their own module so the core lib has fewer dependencies.
