### ISSUE TITLE
The way to set and control manual Ack 

### ISSUE THREAD

**Issue by zhangwm1987** [cloudevents/sdk-go#586]
## Description

Basically i want use manual Ack for NATS streaming, when my receive handler get some error, i do not want send ack to nats server.

I found i can use the receive handler like below:
```
//func(context.Context, event.Event) (*event.Event, protocol.Result)
StartReceiver(ctx context.Context, fn interface{}) error
```
My receive function:
```
func receive(_ context.Context, event cloudevents.Event) (*event.Event, protocol.Result) {
...
}
```

I can use the return value  protocol.Result to control whether send the manual ack or not to nats server.

## Issue

When i use above function as my receive function,  i got below error:

	if invoker.IsResponder() && c.responder == nil {
		return fmt.Errorf("mismatched receiver callback without protocol.Responder supported by protocol")
	}
The invoker.IsResponder() seems check the number of return values.  But how to set the c.responder.  

For nats streaming do cloud event lib support the receive function like above?   Can the samples been updated for some manual ACK cases?

**Comment by slinkydeveloper** [comment]
The handler you found it's to support request/response, but nats doesn't support it. Maybe are you looking for `func(context.Context, event.Event) protocol.Result`?

**Comment by zhangwm1987** [comment]
Yes, i think this can meet my requirment. Thanks
