### ISSUE TITLE
Allow customization of which errors to retry.

### ISSUE THREAD

**Issue by vaikas** [cloudevents/sdk-go#595]
https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/http/protocol_retry.go#L45

These are hard coded, would it be possible to pass this in somehow. I think using context might be a bit hacky, but a thought.

**Comment by slinkydeveloper** [comment]
I'm not sure, it shouldn't go in cecontext.RetryParams because it's an http specific config value... Maybe in https://github.com/cloudevents/sdk-go/blob/master/v2/protocol/http/options.go ?

**Comment by vaikas** [comment]
sounds good. I'll take a crack.
/assign
