### ISSUE TITLE
CloudFunctions Function Build failed

### ISSUE THREAD

**Issue by kiyor-cai-exa** [cloudevents/sdk-go#601]
I got this error start from today, same code, same everything, just build failed.

Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Build failed: # github.com/cloudevents/sdk-go/v2/extensions
src/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go:161:3: cannot use span (type trace.Span) as type *trace.Span in return argument:
 	*trace.Span is pointer to interface, not interface; Error ID: xxx

**Comment by slinkydeveloper** [comment]
We don't have any "CloudFunctions" in this project, are you referring to another project that uses this library behind the hood?

**Comment by danmrichards** [comment]
I believe @kiyor-cai-exa is referring to Google Cloud Functions. We're seeing a similar issue at the moment too. It appears that Google has broken their runtime environment for Golang 1.13.

I'd make a guess that they've upgraded a version of this package without its appropriate dependencies.

**Comment by publiclou** [comment]
I got the issue in this morning too.
Try to change file structure like this [https://cloud.google.com/functions/docs/writing#structuring_source_code](https://cloud.google.com/functions/docs/writing#structuring_source_code)
It seem like **go.mod must in the same level with your functions**.

**Comment by slinkydeveloper** [comment]
@kiyor-cai-exa @danmrichards @publiclou You need to open an issue in their repository then (or ask to their support). I'm gonna close this since it's unrelated to this project.

**Comment by danmrichards** [comment]
Yep agreed, not your problem @slinkydeveloper. Thanks for the replies.

**Comment by RobinUS2** [comment]
we're having similar issues as of today.

**Comment by pnuaxen** [comment]
We are seeing this error today also and unable to deploy using Go 1.13 runtime
