### ISSUE TITLE
Sleep required when posting to NATS

### ISSUE THREAD

**Issue by mpejcoch** [cloudevents/sdk-go#608]
In the sample code, there is a `time.Sleep(100 * time.Millisecond)` statement at the end of the function:
https://github.com/cloudevents/sdk-go/blob/master/samples/nats/sender/main.go

From what I have seen, this is needed as without it some messages might not be delivered, however it seems strange to be relying on a Sleep(). Why is it needed? And is there some other way around the issue?

**Comment by slinkydeveloper** [comment]
I guess this was made by @n3wscott or @dan-j, can you provide more info on this one?

**Comment by dan-j** [comment]
I've no idea, seems that sample was written 2 years ago, way before I joined in. 

@mpejcoch have you tested what happens if the `Sleep()` is removed? I haven't actually used this SDK nor the NATS SDK to send events/messages, only to receive (all my publishers are NodeJS), but it does seem strange if it's required.

**Comment by mpejcoch** [comment]
I did not try directly with the sample, but we have almost identical code based on the sample. The result of not having the `Sleep()` is that the messages just won't be published sometimes, even though the `IsUndelivered(result)` returns false and `IsACK` is `true`. This makes it difficult to use in production code.

https://github.com/metno/go-mms/blob/adf1b6047063b175355afc77b7569478ba93249a/pkg/mms/events.go#L177

I suppose that the workaround for us would be to only use the Cloudevents SDK to create the message and interact with NATS directly or via https://gocloud.dev/howto/pubsub/, but I wanted to check with you, whether it's a known issue and if there is a chance it will get fixed.

**Comment by dan-j** [comment]
I'm struggling to see how the `Sleep()` can actually affect the publishing of messages. The underlying NATS cloudevents protocol calls `Publish()` which is a sync operation, there's nothing async about it. 

How have you verified that messages aren't being published? Have you tried subscribing to the NATS server from their sample CLI commands? https://github.com/nats-io/nats.go/tree/master/examples/nats-sub

**Comment by mpejcoch** [comment]
I have tested with the nats.go subscriber, the thing is that I cannot reproduce this with the example from cloudevents, for our code I see the message not being deliver occasionally, but then it is consistently not received by our receiver nor the one from nats.go. So I think that the `Sleep()` statement plays some role in our code, but the real problem is somewhere else, will search more, sorry for the distraction.

**Comment by dan-j** [comment]
Feel free to post some code and I can take a quick look, see if there's anything hidden in plain sight?

**Comment by mpejcoch** [comment]
Thanks, the code is in the repo I linked to above, though I think we have found the issue now, the NATS connection hasn't been closed properly: https://github.com/metno/go-mms/pull/54/files

The `Sleep()` was thus a distraction as I assume that in your example it's there to illustrate a real-world message flow, but in our code it was used as a workaround and we have been mislead thinking that your example too depends on the `Sleep()` line for it to work.

**Comment by dan-j** [comment]
I think this can be closed now @slinkydeveloper

**Comment by slinkydeveloper** [comment]
Thanks for checking this out @dan-j
