### ISSUE TITLE
How to add http headers for cloudevent in v2

### ISSUE THREAD

**Issue by boblee0717** [cloudevents/sdk-go#654]
For each cloudevent, I want to add some specify headers.
In v1, you can use `transport/http.ContextWithHeader` to add headers.
However, in v2, I can not find the same interface.
In v2, I can only add headers for client, is there any way to add headers for different cloudevents?

**Comment by slinkydeveloper** [comment]
A PR for this issue was recently merged: https://github.com/cloudevents/sdk-go/pull/646 This will be included in the 2.4 release

**Comment by boblee0717** [comment]
@slinkydeveloper Awesome, btw, when the SDK 2.4 will release? This feature has been blocking us from migrate SDK from V1 to V2.

**Comment by slinkydeveloper** [comment]
Hopefully soon :smile:
