### ISSUE TITLE
Encode event to http response in V2 sdk

### ISSUE THREAD

**Issue by boblee0717** [cloudevents/sdk-go#655]
In v1, you can use codecvxx to encode an event to transport.Message and put the message into a http response.
However, I can not find the same interface from V2 sdk.
This feature is very useful in some situations - when you proxy a request and want to send back a cloudevent in the middlerware.

**Comment by slinkydeveloper** [comment]
Please check out https://cloudevents.github.io/sdk-go/protocol_implementations.html for more details on Messages
