### ISSUE TITLE
Protobuf codec and format support

### ISSUE THREAD

**Issue by kconwayinvision** [cloudevents/sdk-go#661]
Hey folks, I have an implementation of https://github.com/cloudevents/spec/blob/v1.0.1/protobuf-format.md that I'm looking to contribute. Before I open a PR, I figured I'd give folks a chance to see what is involved. I've put some code up for demonstration here: https://github.com/kconwayinvision/cloudevents-go-protobuf. It's a fairly straightforward implementation of `format.Format`, `datacodec.Encoder`, and `datacodec.Decoder`. The real complexity is in implementing the requirement to use the `ProtoData` field when the format and data codec are both protobuf.

If this belongs in the SDK then I can open a PR for us to talk about more specific issues such as whether or not to automate protobuf code generation or the complexity of the protobuf type juggling. I figured I'd start by asking whether or not this even belongs here or if this should go in a contrib space somewhere.

**Comment by slinkydeveloper** [comment]
Hi @kconwayinvision, thanks for the proposal. We would really love to see the protobuf format, what about starting with a PR for the implementation of `format.Format`?

For the datacodec implementation, let's figure it out after the format

**Comment by kconwayinvision** [comment]
A pull request for the Format is up here: https://github.com/cloudevents/sdk-go/pull/662

**Comment by kconwayinvision** [comment]
If there are folks watching this issue and not the PRs then https://github.com/cloudevents/sdk-go/pull/688 is waiting on reviews.

**Comment by kconwayinvision** [comment]
This is ready to close.

Format support added: https://github.com/cloudevents/sdk-go/pull/662
Codec support added: https://github.com/cloudevents/sdk-go/pull/688
