### ISSUE TITLE
Traces are not generated using v2.4 

### ISSUE THREAD

**Issue by Shashankft9** [cloudevents/sdk-go#682]
While trying to reuse the convention followed in knative-eventing sources to generate traces using cloudevents sdk, I noticed that considerable code has been changed in v2.4 which is being used by the `main` branch of knative-eventing now, like here:

- https://github.com/cloudevents/sdk-go/blob/main/v2/client/client.go#L55 to generate the client. 
- https://github.com/cloudevents/sdk-go/blob/main/v2/client/client.go#L132 to generate traces. 

But, it isnt working for some reason - traces are not generated. To double check, I built the `main` branch of knative-eventing as well, tracing seems to be broken there as well. Note: I have checked for traces generate by sources only. Its working for knative-eventing v0.22 though, which used the go sdk without these code changes). 

For now I have regressed to v2.2  in my project, and it seems to be working fine.

**Comment by n3wscott** [comment]
@slinkydeveloper to comment

**Comment by slinkydeveloper** [comment]
Are you creating the client with this method? https://github.com/cloudevents/sdk-go/blob/main/observability/opencensus/v2/client/client.go#L14

**Comment by Shashankft9** [comment]
I just tried this method, it works - thank you!
Would it make sense to add its alias in `alias.go` as `NewClientHTTPObserved`? It'd be easier to use this method and I'd guess this would also replace the method used by eventing sources since currently they make use of https://github.com/cloudevents/sdk-go/blob/main/v2/client/client.go#L55 to generate the client. 

If it makes sense to you, I can do the changes upstream, I have tried testing in dev env, and with these changes the sources are generating the traces as well.

**Comment by slinkydeveloper** [comment]
@Shashankft9 the idea of the change was to remove the dependency on opencensus, adding to alias.go would reintroduce the dependency on opencensus, so it's a no go for me.

**Comment by Shashankft9** [comment]
@slinkydeveloper does this mean that anything under `cloudevents/sdk-go/observability` is bound to go away later? Or the purpose was just to separate `v2`  from `observability`? I can imagine why doing the latter would makes sense to remove dependency of opencensus on cloudevents versions.

**Comment by slinkydeveloper** [comment]
The latter :) there is no plan today of removing observability, on the contrary we would love to grow observability and add support to the latest techs (like opentelemetry)

**Comment by Shashankft9** [comment]
thank you for clarifying, really helped. 
Closing this issue, would open a PR in eventing with related changes.
