### ISSUE TITLE
Feature request: support jetstream in protocol

### ISSUE THREAD

**Issue by zhaojizhuang** [cloudevents/sdk-go#694]
Feature request: support jetstream in protocol

**Comment by zhaojizhuang** [comment]
As mentioned in this issue https://github.com/cloudevents/sdk-go/issues/258#issuecomment-601693073

**Comment by zhaojizhuang** [comment]
@n3wscott

**Comment by zhaojizhuang** [comment]
cc @ripienaar

**Comment by n3wscott** [comment]
there was a PR but it was breaking, so it did not go in, likely there needs to be a jetstream module made to do the integration
