### ISSUE TITLE
nats_jetstream - Unknown revision error

### ISSUE THREAD

**Issue by mysticmode** [cloudevents/sdk-go#702]
Hi,

When I try to do `go get github.com/cloudevents/sdk-go/protocol/nats_jetstream/v2`.

I'm facing this error:
```
go: downloading github.com/cloudevents/sdk-go/protocol/nats_jetstream/v2 v2.0.0-20210811165601-e0fe15f9daeb
go get: github.com/cloudevents/sdk-go/protocol/nats_jetstream/v2@none updating to
        github.com/cloudevents/sdk-go/protocol/nats_jetstream/v2@v2.0.0-20210811165601-e0fe15f9daeb requires
        github.com/cloudevents/sdk-go/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

I suppose, the problem is with this line - https://github.com/cloudevents/sdk-go/blob/main/protocol/nats_jetstream/v2/go.mod#L8

Could somebody guide me on this? Thanks!

**Comment by n3wscott** [comment]
in go, `v2.0.0-00010101000000-000000000000` means it is using the v2 of the lib, but it using the replace directive. I need to release the next version and that will unblock you. Doing that now. Thanks!

**Comment by mysticmode** [comment]
Sure thing, thank you! I'm closing this issue as I can see the changes in the new release.
