### ISSUE TITLE
Add HTTP Status Code 500 to retryable status codes in default retry handler?

### ISSUE THREAD

**Issue by embano1** [cloudevents/sdk-go#718]
In event-driven topologies, e.g. broker to function, some (many?) developers might choose a generic 500 HTTP status code in case of internal server (function) failure instead of a more precise 5xx code (e.g. 503). 500 is currently not in the list of default retryable status codes. Should we change this?

https://github.com/cloudevents/sdk-go/blob/c6de9589bb3578364689adc64414000dabe93c01/v2/protocol/http/protocol.go#L40

I understand that this might be considered a breaking change.

**Comment by n3wscott** [comment]
I think we did not add 500 because we assumed if it 500'ed on one, it likely will 500 on the next try.

**Comment by n3wscott** [comment]
note you can change this if the SDK's defaults are not working for you: https://github.com/cloudevents/sdk-go/blob/5d1b1734bf73d587a6eac47bd3615b4b4e976e52/v2/protocol/http/options.go#L268-L279

**Comment by embano1** [comment]
Thx Scott. Sorry for the confusion as the question was actually about changing the defaults to include `500`. Will close this one for now since we have a separate thread going on in `knative` to establish certain retry standards there, using `kncloudevents.SelectiveRetry`.
