### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by nachocano** [cloudevents/sdk-go#74]
Should have documentation for Developers explaining how to set up the dev environment, and contribute

**Comment by slinkydeveloper** [comment]
@nachocano is the doc we have now and the website enough?

**Comment by nachocano** [comment]
> @nachocano is the doc we have now and the website enough?

Yes, this is pretty old. Closing

**Comment by nachocano** [comment]
Feel free to reopen if you feel more details are needed
