### ISSUE TITLE
CE HTTP: keep request data at the context

### ISSUE THREAD

**Issue by odacremolbap** [cloudevents/sdk-go#742]
The HTTP CE Client for receiving requests is designed to be used like this:

```golang
...
client := NewClient(options)
err := client.StartReceiver(ctx, dispatch)
...
func dispatch(ctx context.Context, event ce.Event) (*ce.Event, ce.Result) {
   return process(event)
}
```

I would like to have more information on the received request at the CloudEvent client to be able to create multi-tenant clients. That would be:

```golang
func dispatch(ctx context.Context, event ce.Event) (*ce.Event, ce.Result) {
   req  := ce.HTTPRequestFromContext(ctx)
   process := processLookupEventProcessor(req)
   return process(event)
}
```

For this to happen the request or a subset of their data should be added to the context before the switch here:

https://github.com/cloudevents/sdk-go/blob/1170e89edb9b504a806f2c6a26563c3c26b68276/v2/protocol/http/protocol.go#L285-L301

---

The scenario I am working on are generic transformations of CloudEvent payloads where users can configure their own transformation parameters getting a different URL path for each configuration. Requesting the same CloudEvents client at each of those paths would call the dispatcher, and inside it the developer could use the raw request (request.URL.Path in my case) to load the configuration:

- my.ce.transformation/configuration-for-jane
- my.ce.transformation/configuration-for-joan

---

**Alternatives**

- Using the an extended attribute or even the payload to inform the expected configured tenancy.

I have no control on the received events from users, but as a Sinks developer I can expose a distinct URL Address for each configuration. This alternative is not possible for me.

- Not using CE Client.

While this is a solution, I would love to use the retries and abuse protection of the CE Client without duplicating that code at my end.

**Comment by n3wscott** [comment]
Originally the SDK did something like this but it was not very reliable for the other protocols. But I still think it might be ok to add additional values in the context of the message (here https://github.com/cloudevents/sdk-go/blob/1170e89edb9b504a806f2c6a26563c3c26b68276/v2/protocol/http/message.go#L75-L76) and you can probe for them in the invoked receiver (which is what I think you are wanting to do now?)

Would this work for you?

**Comment by odacremolbap** [comment]
Yes, that would be perfect. If I am undertanding that right that would be

```go
message := NewMessage(req.Header, req.Body) 
message.ctx = WithRequest(req.Context(), req)
```

so that I can do later something like

```go
func dispatch(ctx context.Context, event ce.Event) (*ce.Event, ce.Result) {
  req := httpce.RequestFromContext(ctx)

  subDispatcher = dispatchMap[req.URL.Path] // ... and check for !ok
  return subDispatcher(ctx, ce)
}
```

Looking at it it doesn't feel great passing the body reader and letting users mess with it but we can always TeeRead it if that's a concern.

**Comment by n3wscott** [comment]
We can't pass the request because of the reader as you mention. It ends up with EOF exceptions because something else ends up closing that body reader. The full body of the cloudevent should be captured by the cloudevent message, so we should be good there. I think you need maybe the following:

- req.URL
- req.Headers
- req.Host
- req.RemoteAddr

I think that might be the useful safe request fields we can pluck out and inject into the context.

**Comment by n3wscott** [comment]
The way I would do this is I would make a context helper in the cloudevents http package, make a new struct with these fields, copy them over before leaving the serve http method into the context using the helper context method.

Then in your code you can take a context in the receive function and probe the context for the http request context struct, keeping in-mind that it might not be there if you have used a non-http protocol. 

Would you like to PR this up @odacremolbap? I would be more than happy to review and then help the release process along to get it into a release.

**Comment by odacremolbap** [comment]
sure thing!
