### ISSUE TITLE
Unable to recieve events with jetstream on nats-server version 2.6.6

### ISSUE THREAD

**Issue by joshianiket22** [cloudevents/sdk-go#746]
I'm not receiving any events with Jetstream receiver. My cloudevents sdk-go version is 2.6.1 and my nat-server version is 2.6.6 which i recently upgraded to. 

I was able to receive events earlier before i upgraded my nat-server version from 2.2.6 to 2.6.6. So its the version issue or it might be the version of the nats client driver that is being used. Also there is nothing returned from the StartReceiver function, So its actually hard to figure out the underlying cause. Thanks.

**Comment by joshianiket22** [comment]
I figured out that the problem is with the **ConsumerOption** that we pass when creating a new consumer. If we don't pass this option we are able to receive events without any issues, But then we don't have a Queue group created.

**Comment by dan-j** [comment]
Hi @joshianiket22, could you provide some sample code of what does and doesn't work, and describe what type of consumer you're trying to create in NATs-terms, i.e. durable/queue group/standard consumer etc.

If you can provide this I'll try and take a look

**Comment by n3wscott** [comment]
@joshianiket22 I will be honest here and say I don't know much about NATs but I want it to work. Let's get this sorted out and maybe @dan-j can magic up some better way to create a client. 

Sound good @dan-j ?

**Comment by joshianiket22** [comment]
Looks like the version issue was on my end, I apologize. After upgrading everything works smoothly. 
I really appreciate and thank you for reaching out to help me on this @dan-j & @n3wscott :)
We can close the issue.
