### ISSUE TITLE
PubSub subsequent messages not properly ordered by key

### ISSUE THREAD

**Issue by rriolobos** [cloudevents/sdk-go#753]
https://github.com/cloudevents/sdk-go/blob/7601392008ad787e9f27cf1d7898ff14fef1b236/protocol/pubsub/v2/protocol.go#L233

I tested pubsub ordering key with this library but I found an issue. When you send 3 or more messages, with same ordering key, receiver only waits for first one, second and third messages are consumed concurrently. I added a 5 second sleep in message handler in order to check that the total amount of time was 15 seconds as expected, but it was 10 second. It can also be checked with logs. When I try the same directly invoking pubsub receiver, it worked as expected (@skymeyer).
```
func receive(ctx context.Context, event event.Event) error {
	fmt.Printf("Event Context: %+v\n", event.Context)

	fmt.Printf("Protocol Context: %+v\n", pscontext.ProtocolContextFrom(ctx))

	data := &Example{}
	if err := event.DataAs(data); err != nil {
		fmt.Printf("Got Data Error: %s\n", err.Error())
	}

	time.Sleep(8 * time.Second)

	fmt.Printf("Data processed: %+v\n", data)

	fmt.Printf("----------------------------\n")

	return nil
}

func main() {
	ctx := context.Background()

	var env envConfig
	if err := envconfig.Process("", &env); err != nil {
		log.Printf("[ERROR] Failed to process env var: %s", err)
		os.Exit(1)
	}

	t, err := cepubsub.New(context.Background(),
		cepubsub.WithProjectID(env.ProjectID),
		cepubsub.WithTopicID(env.TopicID),
		cepubsub.WithReceiveSettings(&pubsub.ReceiveSettings{}),
		cepubsub.WithSubscriptionID(env.SubscriptionID))
	if err != nil {
		log.Fatalf("failed to create pubsub protocol, %s", err.Error())
	}

	t.ReceiveSettings.NumGoroutines = 1

	c, err := cloudevents.NewClient(t)

	if err != nil {
		log.Fatalf("failed to create client, %s", err.Error())
	}

	log.Println("Created client, listening...")

	if err := c.StartReceiver(ctx, receive); err != nil {
		log.Fatalf("failed to start pubsub receiver, %s", err.Error())
	}
}
```

**Comment by skymeyer** [comment]
@rriolobos I have updated your sample code a bit to try to reproduce and created two samples:

- [Without ordering](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-no-order-main-go) --> [output](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-no-order-output-txt)
- [With ordering](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-with-order-main-go) --> [output](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-with-order-output-txt)

Ordering seems to work as expected on my end. Can you review a couple of things (ranked from most to less likely) as the message ordering seems to work for me:

- Using [`MaxOutstandingMessages`](https://github.com/googleapis/google-cloud-go/blob/pubsub/v1.17.1/pubsub/subscription.go#L523-L528)may just solve your problem
- Also verify that your subscription in GCP has explicitly "message ordering" enabled
- See my [note on regional endpoint usage](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-with-order-main-go-L54-L58)
- Review your events were properly produced with an ordering key set (see [example](https://gist.github.com/skymeyer/14d6e45321574241d50647b2f03fb3b4#file-pubsub-with-order-main-go-L94-L112))

Hope that helps shed some light. I have not tested letting `cloudevents` sdk create the topic/subscription dynamically. I had them preconfigured. Are you relying on the auto creation ?

**Comment by rriolobos** [comment]
Hi @skymeyer,

First of all thanks for your answer.

You are right, I mean, when I set MaxOutstandingMessages=1 messages are properly ordered. In fact, all messages are ordered, both for same key and different one. Let's try with an example:
Let's imagine every message is process in 5 seconds and prints 2 logs: start message 5s -> end message
Imagine we have the following sequence without setting MaxOutstandigMessages=1:

A,B,C,A,A

I expect the following output;
Start A
StartB
StartC
EndA
StartA
EndB
EndC
EndA
StartA
StartB

I mean, hope messages with different key are processed concurrently and messages with same key are processes sequentially.

Is it possible to get this behavior based on some specific settings?
I'm not sure this is a cloudevent behavior or in fact it is a pubs one because I am trying directly with pubs library and do not get the expected behavior either.

Best regards.

**Comment by n3wscott** [comment]
I believe the linked PR corrected this issue with the corresponding config set on the transport instance. Closing, please reopen if this was not solved.
