### ISSUE TITLE
CLOMonitor metadata

### ISSUE THREAD

**Issue by duglin** [cloudevents/sdk-go#767]
See: https://clomonitor.io/projects/cloudevents/cloudevents
Can we get the appropriate updates so that the CLOMonitor tool is happy?
More info on CLOMonitor checks: https://github.com/cncf/clomonitor/blob/main/docs/checks.md

**Comment by duglin** [comment]
Looks like we're just missing a MAINTAINERS file:
![image](https://user-images.githubusercontent.com/1944671/162205154-5274980d-dcb8-47c4-8ca5-093d93fed444.png)

**Comment by n3wscott** [comment]
ok will add.
