### ISSUE TITLE
The sender can't get the error message from receiver

### ISSUE THREAD

**Issue by wenfengwang** [cloudevents/sdk-go#783]
Hi `sdk-go` community, I started a receiver like:
```go
func receive(ctx context.Context, event cloudevents.Event) cloudevents.Result {
	fmt.Printf("Got an Event: %s", event)
	return cloudevents.NewHTTPResult(401, "test")
}
```
but the sender can't get the error message:
![image](https://user-images.githubusercontent.com/9766821/179494617-a976cdaa-c83b-4a81-b36b-6f2866a9b779.png)

and I found in https://github.com/cloudevents/sdk-go/blob/main/v2/protocol/http/protocol.go#L366, that only `StatusCode` be used, but `Format` and `Args` are ignored.
![image](https://user-images.githubusercontent.com/9766821/179495129-445e504c-c2b0-418a-9418-14d44c46ebe4.png)

I was wondering if it was a bug?

**Comment by n3wscott** [comment]
Seems like a bug, want to fix?

**Comment by wenfengwang** [comment]
> Seems like a bug, want to fix?

OK, I will submit a PR to fix this.

**Comment by n3wscott** [comment]
Thanks for the PR!!
