### ISSUE TITLE
Yaml V2 Vulnerability

### ISSUE THREAD

**Issue by reachlakstar** [cloudevents/sdk-go#788]
FORTIFY is throwing Yaml V2 vulnerabilities, could you please migrate to new versions
OR
Please get rid of this dependancy
github.com/stretchr/testify v1.5.1

**Comment by n3wscott** [comment]
Thanks for the report. Will look into it.

**Comment by reachlakstar** [comment]
@n3wscott if you migrate the go.mod version of github.com/stretchr/testify 1.8.0 this will go away.

**Comment by reachlakstar** [comment]
@n3wscott when do you think this will be released

**Comment by n3wscott** [comment]
I can make a new release after I get a review on https://github.com/cloudevents/sdk-go/pull/790
