### ISSUE TITLE
Can't send custom type using SetExtension

### ISSUE THREAD

**Issue by Roman-Bober** [cloudevents/sdk-go#789]
I have defined
```
type MyEnum  int
```
However  **failing** to set  as extension the above type instance using 
[event_writer](https://pkg.go.dev/github.com/cloudevents/sdk-go/v2/event#Event.SetExtension)
```
 func (e *Event) SetExtension(name string, obj interface{}) 
...
newEvent.SetExtension("myenum", myEnum )

```

Failure occurs in [value.go](https://github.com/cloudevents/sdk-go/blob/main/v2/types/value.go#L92)
``` 
func Validate(v interface{}) (interface{}, error) 
```
Any ideas on how to send my type(I can use casting to int but it seems unnatural)?
Thanks

**Comment by n3wscott** [comment]
This is correct, there is a type system that is supported by cloudevents at the spec level and you will need to turn your custom value into some kind of supported type, likely a string.
