### ISSUE TITLE
Provide examples how you think people should use Protobuf

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [cloudevents/sdk-go#792]
At least to me the design decisions that this library took are not obvious.
Also I have no idea how the library authors think people should use this library.
Obvious to me would be:

```golang
ev := pb.CloudEvent{}
err := protobufv2.DecodeData(ctx, m.Value, &ev)
```

but as mentioned in other issues that does not work since `pb` package is under `internal` and not at the correct stage.

**Comment by n3wscott** [comment]
I agree. 

I think we should make a full fledged proto transport. What do you think?

**Comment by embano1** [comment]
@AndreasBergmeier6176 can this be closed now that `pb` got moved outside `internal`?

**Comment by AndreasBergmeier6176** [comment]
Indeed. Additional Bonus points would be showing up in buf.build.
