### ISSUE TITLE
Support for TokenSource

### ISSUE THREAD

**Issue by tommed** [cloudevents/sdk-go#796]
I would like my CloudEvents server and client to support OAuth2 access tokens.

For the listening server, I see that I can create a `http.Handler` using `cloudevents.NewHTTPReceiveHandler` which would allow me to wrap this in middleware for checking the `Authorization` header.

However, I am unable to find a way to set the access token on the outgoing/calling client (e.g. `cloudevents.NewClientHTTP`)?
The only `http.Option` I can see that is related is `http.WithHeader` however this requires a static field, not even a callback function - as tokens change regularly, this would not work unless I constantly created new clients all the time 👎 

Given you are creating a `http.Client` for sending requests, in the [oauth2 package](https://pkg.go.dev/golang.org/x/oauth2), there is a way of creating [a new http Client](https://pkg.go.dev/golang.org/x/oauth2#NewClient) and setting a `TokenSource` which manages the `Authorization` header for you.

How can I achieve this same thing whilst using the CloudEvents sdk pls? For example, pseudo code:

```golang
client, err := cloudevents.NewClientHTTP(
    http.WithTarget(bindAddr),
    http.WithTokenSource(tokenSource))
if err != nil {
	return err
}
```

**Comment by n3wscott** [comment]
Howdy! you are able to populate the client inside of the http protocol instance directly, after calling https://github.com/cloudevents/sdk-go/blob/82f2b61ecde41fd0577969cc58a7c2a18eeda250/v2/protocol/http/protocol.go#L92-L118 you can reach in and change the http client, it is exported: https://github.com/cloudevents/sdk-go/blob/82f2b61ecde41fd0577969cc58a7c2a18eeda250/v2/protocol/http/protocol.go#L53 

Then pass that instance of the http protocol into a cloudevents client if you wish to use that:  `cloudevents.NewClient(httpP, options...)`

We could add an option to send in an http client, but I tried to have the break glass option of just setting it directly. Let me know if that will work for you, and perhaps you would like to make a PR to add the outbound http client option? 😄

**Comment by tommed** [comment]
Amazing thanks! :)
