### ISSUE TITLE
change cloudevents.HTTPOption and cloudevents.HTTPOption from type redefine to type alias

### ISSUE THREAD

**Issue by sforests** [cloudevents/sdk-go#804]
hello!
I want to use opts to create client as blow:
```
func main() {
	// instead of `var opts []http.Option`
	//  everything is ok, build pass
	var opts cloudevents.HTTPOption
	opts = append(opts, cloudevents.WithTarget("http://target_url"))
	opts = append(opts, cloudevents.WithShutdownTimeout(5*time.Second))
	// ...  other options

	cloudevents.NewClientHTTP(opts...)
}
```
then, build error occur:
`cannot use v2.WithTarget("http://target_url") (type "github.com/cloudevents/sdk-go/v2/protocol/http".Option) as type v2.HTTPOption in append`

expect:
```
cloudevents/sdk-go/v2/alias.go:24
type ClientOption client.Option -> type ClientOption = client.Option
cloudevents/sdk-go/v2/alias.go:45
type HTTPOption http.Option -> type HTTPOption = http.Option
```
I think it is better to change cloudevents.HTTPOption and cloudevents.HTTPOption from type redefine to type alias.
Is this written for other considerations or a historical legacy?

I already create a pr in here 
#805

**Comment by n3wscott** [comment]
Thanks for the PR!
