### ISSUE TITLE
undefined: v2.NewCloudEventFromHTTPRequest

### ISSUE THREAD

**Issue by rnotorni** [cloudevents/sdk-go#835]
[This pull request]( https://github.com/cloudevents/sdk-go/pull/799/files) has a difference between the document and the implementation.

The document defines it as `NewCloudEventFromHTTPRequest`, but it is actually `NewEventFromHTTPRequet`.

**Comment by embano1** [comment]
Good catch, want to file a doc PR?

**Comment by rnotorni** [comment]
@embano1 Thank you for the confirmation!

I will issue a PR for the Document.
