### ISSUE TITLE
Add `test.HasExtensionsKeys` assertion helper

### ISSUE THREAD

**Issue by embano1** [cloudevents/sdk-go#900]
Sometimes it might be helpful to have an assertion helper in integration tests to assert that specific extension keys are present in the produced `outEvent`, not knowing the extension values upfront, such as when the transport adds extensions. The current helpers always compare extension keys and values which fails the test.

Proposing `test.HasExtensionsKeys` to only assert that a specific extension key is set if the value is not known upfront/not of interest during assertions.

Ref: https://github.com/cloudevents/sdk-go/pull/896/files#r1203500742

**Comment by yanmxa** [comment]
@embano1 How about adding an event matcher like this:
```go
func HasExtensionKeys(keys []string) EventMatcher {
	return func(have event.Event) error {
		for _, k := range keys {
			if _, ok := have.Extensions()[k]; !ok {
				return fmt.Errorf("expecting extension '%s'", keys)
			}
		}
		return nil
	}
}
```
This is similar to the [HasExtensions](https://github.com/cloudevents/sdk-go/blob/fdcb2d226a0aa4f64c7d7c0d5b33adf64e0c06c7/v2/test/event_matchers.go#L173)

**Comment by embano1** [comment]
+1

`return fmt.Errorf("expecting extension '%s'", keys)` should be `return fmt.Errorf("expecting extension key %q", k)`
