### ISSUE TITLE
Whether to consider adding MQTT protocol binding

### ISSUE THREAD

**Issue by yanmxa** [cloudevents/sdk-go#901]
I found the [cloudevetns/spec](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/mqtt-protocol-binding.md) which describes the MQTT binding, Do we consider adding the implementation for the sdk-go?

**Comment by duglin** [comment]
@yanmxa I don't see it on anyone's TODO list, so if you're offering to submit a PR to add it I'm sure it would be welcome :-)

**Comment by yanmxa** [comment]
@duglin Okay~
Let me add it to my to-do list.

**Comment by davidjungermann** [comment]
This would be great for our use case!
