### ISSUE TITLE
Is it correct to use like this?

### ISSUE THREAD

**Issue by mplmoknijb** [cloudevents/sdk-go#907]
When I use the "sendData" method of Cloudevents and try to receive it using gRPC, I find that I'm not correctly getting the data. 

finally, I retrieve the data with the following code. Could you please let me know what I might be doing wrong?

### sender
```go
c, err := cloudevents.NewClientHTTP()
	if err != nil {
		log.Fatalf("failed to create client, %v", err)
	}

	// Create an Event.
	event := cloudevents.NewEvent()
	event.SetID("A234-1234-1234")
	event.SetSource("haa/api/v1/pull")
	event.SetType("haa.pull")
	// optional
	event.SetExtension("haaext", "extval")

	// Set a target.
	url := "http://localhost:8080"
	bytes, err := json.Marshal(event)
	ctx := cloudevents.ContextWithTarget(context.Background(), url)

	event.SetData(cloudevents.ApplicationJSON, map[string][]byte{"event": bytes})
	// Send that Event.
	if result := c.Send(ctx, event); cloudevents.IsUndelivered(result) {
		log.Fatalf("failed to send, %v", result)
	} else {
		log.Printf("sent: %v", event)
	}
``` 

### receiver
```proto
service StreamService {
  rpc Receiver(HaaRequest) returns (Response);
}

message HaaRequest {
  bytes event = 1;
}

```
```go
func (h *HaaServer) Receiver(ctx context.Context, req *pb.HaaRequest) (*pb.Response, error) {
    event := cloudevents.NewEvent()
    err := json.Unmarshal(bytes, &event)
    fmt.Println(event)
    return tools.Response(err, "receive success")
}
```

**Comment by duglin** [comment]
if I'm reading this correctly, I think your event `data` will actually be a CloudEvent, and not just some random CloudEvent but the same CloudEvent you're creating. Meaning, I think you're kind of being recursive:

```
bytes, err := json.Marshal(event)
...
event.SetData(cloudevents.ApplicationJSON, map[string][]byte{"event": bytes})
```
Do I have this right? If so, that's a bit odd, isn't it?

**Comment by duglin** [comment]
What should the "data" of the event be?

**Comment by jevon1994** [comment]
> What should the "data" of the event be?

Appreciate your reply. Assertive that the issue stemmed from my usage. The problem I encountered was due to the lack of metadata when receiving the events.

I am now able to retrieve the metadata within the gRPC interceptor.

**Comment by jevon1994** [comment]
> If you're in gRPC land, why not use CE [`proto`](https://github.com/cloudevents/spec/blob/main/cloudevents/formats/cloudevents.proto) ([SPEC](https://github.com/cloudevents/spec/blob/main/cloudevents/formats/protobuf-format.md))?

Thanks for your suggestion, and I will try this

**Comment by embano1** [comment]
@mplmoknijb can this be closed?

**Comment by mplmoknijb** [comment]
> @mplmoknijb can this be closed?
yeap, this can be closed
