### ISSUE TITLE
remove the usage of deprecated ioutil functions

### ISSUE THREAD

**Issue by yanmxa** [cloudevents/sdk-go#921]
With the two proposals (https://github.com/golang/go/issues/42026 and https://github.com/golang/go/issues/40025) has accepted, the package `io/ioutil` will be deprecated and new code is encouraged to use the respective implementations in the packages `io` and `os`.

Ref: https://github.com/search?q=repo%3Acloudevents%2Fsdk-go%20io%2Fioutil&type=code

**Comment by duglin** [comment]
want to submit a PR? :-)
