### ISSUE TITLE
Set up branch protection for `main`

### ISSUE THREAD

**Issue by embano1** [cloudevents/sdk-go#925]
Suggesting to set up `branch` protection rule for `main`, requiring:

- PRs before committing to `main`
- Min 1 approval
- Approval must be on recent push and will be dismissed on new pushes
- Status checks on `build` to pass (prevent commits bypassing CI)
- Settings apply to administrators as well

**Comment by embano1** [comment]
cc/ @duglin @lionelvillard for feedback (rule is already in place, but not active - see `main2` in branch protection)

**Comment by duglin** [comment]
sounds good to me

**Comment by lionelvillard** [comment]
sounds good to me

**Comment by embano1** [comment]
Done
