### ISSUE TITLE
(Urgent) Need to change some dependency

### ISSUE THREAD

**Issue by MeowSaiGithub** [cloudevents/sdk-go#928]
"github.com/Shopify/sarama" is changed to "github.com/IBM/sarama". Having some problem in NewSender().

**Comment by duglin** [comment]
I'm confused. Where was this changed?

**Comment by lionelvillard** [comment]
@duglin https://github.com/IBM/sarama/issues/2461#issuecomment-1620276868

**Comment by embano1** [comment]
We are still using < `1.40` and the redirects are still in place. @MeowSaiGithub what is the error you're facing?

**Comment by MeowSaiGithub** [comment]
sorry about being late, i forgot creating this issue, the issue is already fixed so will close this ticket now. thanks you all for fast fixes.
