### ISSUE TITLE
NATS Jetstream protocol binding - support new jetstream package

### ISSUE THREAD

**Issue by g41797** [cloudevents/sdk-go#942]
According to go.mod sdk uses old version of nats package:
```go
github.com/nats-io/nats.go v1.13.1-0.20220308171302-2f2f6968e98d
```

Current version:
```go
github.com/nats-io/nats.go v1.30.0
```
it's important to note, that new *jetstream* package was added to nats.go

If you need this improvement - please assign this issue to me

**Comment by stephen-totty-hpe** [comment]
@g41797
BTW, I tried to update the nats.go packages during my PR: https://github.com/cloudevents/sdk-go/pull/929
There is a requirement to be backwards compatible with go 1.17 (which is pretty old at this point)
It looks like nats.go can be safely upgraded to v1.22.0 if I am reading the history correctly:
https://github.com/nats-io/nats.go/commit/ba8a129c9502d4b065a52ba0668332dcba15d7f5
which went into nats.go v1.23.0

Also, you will need to update all of the packages that use nats.go, as some of the packages cross boundaries like the tests.

**Comment by g41797** [comment]
- latest nats.go/jetstream requires go 1.20 
- nats.go v1.23 does not contain jetstream package

regarding tests - i implemented [some tests](https://github.com/g41797/syslog2nats/blob/main/msgproducer_test.go) for jetstream based code
nats allows embedding mode useful during test - looks this mode is not used in ce sdk-go
i'd like to contribute
any ideas

**Comment by stephen-totty-hpe** [comment]
this was the comment on my PR:
```
@stephen-totty-hpe we are not using Go 1.18 w/ Generics yet. Can you please revert the mod related changes to dependencies not using Generics? Might have to use an older version of Go (1.17) to do that. Reason being that we state 1.17 as supported version/compatibility in this SDK for users.
```

**Comment by g41797** [comment]
i am pretty sure that generics are not used in nats
let's leave jetstream aside
did you think about another improvement/feature?
