### ISSUE TITLE
cloudEvent client error: “invalid CloudEvents value:(*string)(nil)”

### ISSUE THREAD

**Issue by kycheng** [cloudevents/sdk-go#991]
I used SetExtension to set a null pointer to string and got this error.

https://github.com/cloudevents/sdk-go/blob/39fe13d4806f5815a524a916879b3a760fbdfd51/v2/types/value.go#L146-L150

Code verification null pointer error.

Can we set data to zero value when we encounter null pointer?

**Comment by duglin** [comment]
Can you show me your code that calls this?
